import {useEffect,useState} from 'react';
import {Landmark,Plus,Shield,Users} from 'lucide-react';
const call=async(path:string,options?:RequestInit)=>{const r=await fetch('/api'+path,{credentials:'include',headers:{'Content-Type':'application/json'},...options});const x=await r.json();if(!r.ok)throw Error(x.error||'Request failed');return x};
const resources=['cash','foodstuffs','timber','fibers','basic_metals','energy','strategic_minerals','textiles','processed_foods','construction_materials','basic_goods','consumer_goods','military_equipment','luxury_goods'];

export default function AllianceScreen({mode='directory'}:{mode?:'directory'|'mine'}){
  const[data,setData]=useState<any>(),[detail,setDetail]=useState<any>(),[error,setError]=useState('');
  const open=async(id:string)=>setDetail(await call('/alliances/'+id));
  const load=async()=>{try{const d=await call('/alliances');setData(d);const linked=new URLSearchParams(window.location.search).get('alliance');if(linked&&mode==='directory')await open(linked);else if(mode==='mine'&&d.membership)await open(d.membership.allianceID)}catch(e){setError((e as Error).message)}};
  useEffect(()=>{void load()},[]);
  const action=async(path:string,body:object,method='POST')=>{try{setError('');await call(path,{method,body:JSON.stringify(body)});await load()}catch(e){setError((e as Error).message)}};
  if(!data)return <section className="panel wide">Loading Alliances…</section>;
  if(mode==='mine'&&!data.membership)return <section className="panel wide"><Shield/><span className="eyebrow">MY ALLIANCE</span><h2>Your nation is independent</h2><p>Use the Alliance List directory to discover an organization, submit an application, or create your own Alliance.</p></section>;
  if(detail)return <AllianceDetail data={detail} back={()=>setDetail(undefined)} action={action} reload={open}/>;
  return <><section className="alliance-hero"><Shield/><div><span className="eyebrow">PLAYER ORGANIZATIONS</span><h2>Alliances</h2><p>Pool resources, coordinate growth, collect shared taxes, and protect your nations together.</p></div></section>{error&&<p className="error notice">{error}</p>}<CreateAlliance action={action}/><div className="alliance-grid">{data.alliances.map((a:any)=><button className="panel alliance-card" onClick={()=>open(a.id)} key={a.id}><span className="eyebrow">LEVEL {a.level} · {a.joinPolicy.replace('_',' ')}</span><h3>{a.name}</h3><p>{a.description||'No public description.'}</p><div><b><Users size={14}/>{a.members} members</b><b>{a.taxRate}% tax</b></div></button>)}</div></>;
}

function CreateAlliance({action}:{action:(p:string,b:object,m?:string)=>void}){const[open,setOpen]=useState(false);if(!open)return <button className="primary create-alliance" onClick={()=>setOpen(true)}><Plus size={15}/> Create an Alliance</button>;return <form className="panel alliance-create" onSubmit={e=>{e.preventDefault();action('/alliances',Object.fromEntries(new FormData(e.currentTarget)))}}><h2>Found an Alliance</h2><label>Name<input name="name" minLength={3} maxLength={80} required/></label><label>Description<textarea name="description" maxLength={1000}/></label><div className="form-pair"><label>Membership<select name="joinPolicy"><option value="apply">Applications</option><option value="open">Open membership</option><option value="invite_only">Invite only</option></select></label><label>Community link<input name="communityURL" type="url" placeholder="https://discord.gg/…"/></label></div><button className="primary">Create Alliance</button></form>}

function AllianceDetail({data,back,action,reload}:{data:any;back:()=>void;action:(p:string,b:object,m?:string)=>Promise<void>;reload:(id:string)=>Promise<void>}){
  const a=data.alliance,[resource,setResource]=useState('cash'),[amount,setAmount]=useState(1000),[message,setMessage]=useState('');
  const transfer=async(kind:string)=>{await action(`/alliances/${a.ID}/bank`,{kind,resource,amount,memo:message});await reload(a.ID)};
  return <><button className="back" onClick={back}>← Alliance directory</button><section className="alliance-profile panel"><div><span className="eyebrow">LEVEL {a.Level} ALLIANCE</span><h2>{a.Name}</h2><p>{a.Description||'No public description.'}</p></div><div className="alliance-policy"><span>{a.JoinPolicy.replace('_',' ')}</span><b>{a.TaxRate}% Alliance tax</b></div></section>{!data.isMember&&<button className="primary" onClick={()=>action(`/alliances/${a.ID}/apply`,{message:''})}>{a.JoinPolicy==='open'?'Join Alliance':'Submit application'}</button>}{data.permissions?.tax&&<AllianceSettings a={a} save={async body=>{await action(`/alliances/${a.ID}`,body,'PATCH');await reload(a.ID)}}/>}{data.permissions?.members&&data.applications?.length>0&&<section className="panel"><h2>Pending applications</h2>{data.applications.map((x:any)=><div className="alliance-member" key={x.id}><div><b>{x.nation}</b><span>{x.message||'No application message'}</span></div><button className="primary" onClick={()=>action(`/alliances/${a.ID}/applications/${x.id}/accept`,{})}>Accept</button></div>)}</section>}<div className="alliance-layout"><section className="panel"><h2>Members</h2>{data.members.map((m:any)=><div className="alliance-member" key={m.nationID}><div><b>{m.name}</b><span>{m.userType}</span></div><strong>{m.role}</strong></div>)}</section>{data.isMember&&<section className="panel alliance-bank"><Landmark/><h2>Alliance Bank</h2><div className="bank-grid">{resources.map(r=><div key={r}><span>{r}</span><b>{r==='cash'?'¥':''}{Number(data.bank[r]||0).toLocaleString()}</b></div>)}</div><div className="bank-controls"><select value={resource} onChange={e=>setResource(e.target.value)}>{resources.map(r=><option key={r}>{r}</option>)}</select><input type="number" min="1" value={amount} onChange={e=>setAmount(Number(e.target.value))}/><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Memo"/><button onClick={()=>transfer('deposit')}>Deposit</button>{data.permissions.bank&&<button className="primary" onClick={()=>transfer('withdrawal')}>Withdraw</button>}</div></section>}</div>{data.isMember&&<section className="panel"><h2>Bank audit log</h2>{data.transactions.map((t:any,i:number)=><div className="bank-log" key={i}><span>{new Date(t.createdAt).toLocaleString()}</span><b>{t.actor}</b><span>{t.kind}</span><strong>{t.resource==='cash'?'¥':''}{Number(t.amount).toLocaleString()} {t.resource}</strong><small>{t.memo}</small></div>)}</section>}</>;
}

function AllianceSettings({a,save}:{a:any;save:(body:object)=>void}){return <details className="panel alliance-settings"><summary>Alliance settings</summary><form onSubmit={e=>{e.preventDefault();save(Object.fromEntries(new FormData(e.currentTarget)))}}><label>Description<textarea name="description" defaultValue={a.Description}/></label><div className="form-pair"><label>Membership<select name="joinPolicy" defaultValue={a.JoinPolicy}><option value="open">Open</option><option value="apply">Applications</option><option value="invite_only">Invite only</option></select></label><label>Alliance tax %<input name="taxRate" type="number" min="0" max="100" step="0.1" defaultValue={a.TaxRate}/></label></div><div className="form-pair"><label>Minimum cities<input name="minimumCities" type="number" min="1" defaultValue={a.MinimumCities}/></label><label>Minimum nation age<input name="minimumAgeDays" type="number" min="0" defaultValue={a.MinimumAgeDays}/></label></div><label>Minimum Infrastructure<input name="minimumInfrastructure" type="number" min="0" defaultValue={a.MinimumInfrastructure}/></label><input name="communityURL" type="url" defaultValue={a.CommunityURL}/><button className="primary">Save Alliance settings</button></form></details>}
