import {useEffect,useMemo,useState} from 'react';
import {Building2,Coins,Factory,Landmark,Plus} from 'lucide-react';

const request=async(path:string,options?:RequestInit)=>{const r=await fetch('/api'+path,{credentials:'include',headers:{'Content-Type':'application/json'},...options});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data};
const yen=(n:number)=>`¥${Math.round(n||0).toLocaleString()}`;
const pct=(n:number)=>`${(n*100).toFixed(1)}%`;

export default function EconomyScreen(){
  const[data,setData]=useState<any>(),[cityMeta,setCityMeta]=useState<any>(),[cityName,setCityName]=useState(''),[error,setError]=useState(''),[amount,setAmount]=useState(50),[selected,setSelected]=useState<Record<string,string>>({});
  const load=()=>Promise.all([request('/economy'),request('/cities')]).then(([economy,cities])=>{setData(economy);setCityMeta(cities)}).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);
  const act=async(path:string,method:string,body:object)=>{try{setError('');await request(path,{method,body:JSON.stringify(body)});await load()}catch(e){setError((e as Error).message)}};
  const groups=useMemo(()=>{const x:Record<string,any[]>={};for(const b of data?.buildings||[])(x[b.category]??=[]).push(b);return x},[data]);
  if(!data)return <section className="panel wide">Building the national accounts…</section>;
  const n=data.nation,r=data.result;
  return <div className="economy-v2">
    <section className="income-hero"><Coins/><div><span className="eyebrow">NEXT HOURLY TURN · {new Date(data.nextTurnAt).toLocaleTimeString()}</span><h2>{yen(r.netDailyCash/24)} <small>net per hour</small></h2><p>{yen(r.dailyTax)} daily tax revenue − {yen(r.dailyUpkeep)} infrastructure upkeep</p></div></section>
    {error&&<p className="error notice">{error}</p>}
    <section className="panel city-founder"><div><span className="eyebrow">MULTI-CITY DEVELOPMENT</span><h2>Found a specialized city</h2><p>Additional cities rise sharply in price and require seven real days between foundings.</p><small>{cityMeta?.nextCityAt&&new Date(cityMeta.nextCityAt)>new Date()?`Available ${new Date(cityMeta.nextCityAt).toLocaleString()}`:`Available now · ${yen(cityMeta?.newCityCost||50000)}`}</small></div><div><input value={cityName} onChange={e=>setCityName(e.target.value)} placeholder="New city name"/><button className="primary" disabled={!cityName.trim()||Boolean(cityMeta?.nextCityAt&&new Date(cityMeta.nextCityAt)>new Date())} onClick={()=>act('/cities','POST',{name:cityName})}><Plus size={15}/> Found city</button></div></section>
    <section className="panel policy"><div><span className="eyebrow">NATIONAL POLICY</span><h2>Taxation and doctrine</h2><p>Higher taxation raises immediate revenue but pulls Happiness toward a lower equilibrium.</p></div><label>Tax rate <b>{n.taxRate}%</b><input type="range" min="10" max="45" step="1" value={n.taxRate} onChange={e=>setData({...data,nation:{...n,taxRate:Number(e.target.value)}})}/></label><label>Doctrine<select value={n.doctrine} onChange={e=>setData({...data,nation:{...n,doctrine:e.target.value}})}><option>Balanced</option><option>Capitalist</option><option>Planned</option><option>Green</option></select></label><button className="primary" onClick={()=>act('/economy/policy','PATCH',{taxRate:n.taxRate,doctrine:n.doctrine})}>Adopt policy</button></section>
    <div className="population-strip"><Metric label="Population" value={Math.round(r.population).toLocaleString()}/><Metric label="Happiness" value={`${n.happiness.toFixed(1)} → ${r.happinessTarget.toFixed(1)}`}/><Metric label="Education" value={`${n.education.toFixed(1)} (${r.educationChange>=0?'+':''}${r.educationChange.toFixed(2)}/day)`}/><Metric label="Technology" value={String(n.technology)}/></div>
    <section className="project-section"><div className="section-intro"><span className="eyebrow">TIER I NATIONAL PROJECTS</span><h2>Choose the foundations of your economy</h2><p>{data.projectsCompleted} of {data.projectSlots} unlocked project slots used. Each additional 300 total national Infrastructure unlocks another slot.</p></div><div className="project-grid">{data.projects.map((p:any)=><article className={'panel project-card '+(p.completed?'complete':'')} key={p.key}><span className="eyebrow">{p.theme}</span><h3>{p.name}</h3><p>{p.description}</p><small>{yen(p.cash)}{p.iron?` · ${p.iron} Iron`:''}{p.steel?` · ${p.steel} Steel`:''}{p.aluminum?` · ${p.aluminum} Aluminum`:''}{p.coal?` · ${p.coal} Coal`:''}{p.food?` · ${p.food} Food`:''}</small><button className="primary" disabled={p.completed||data.projectsCompleted>=data.projectSlots} onClick={()=>act('/economy/projects','POST',{project:p.key})}>{p.completed?'Project complete':'Complete project'}</button></article>)}</div></section>
    <div className="city-grid">{r.cities.map((c:any)=><section className="panel city-card" key={c.id}><div className="city-title"><Building2/><div><span className="eyebrow">{c.used} / {c.slots} SLOTS USED</span><h2>{c.name}</h2></div></div><div className="economic-metrics"><Metric label="Effective population" value={Math.round(c.effectivePopulation).toLocaleString()}/><Metric label="Commerce" value={`${c.commerce.toFixed(1)}%`}/><Metric label="Power" value={`${c.powerUsage.toFixed(1)} / ${c.powerCapacity.toFixed(1)}`}/><Metric label="Pollution" value={c.pollution.toFixed(1)}/><Metric label="Disease" value={pct(c.disease)}/><Metric label="Crime" value={pct(c.crime)}/></div><div className="development-row"><input type="number" min="1" max="1000" value={amount} onChange={e=>setAmount(Number(e.target.value))}/><button onClick={()=>act('/economy/development','POST',{cityID:c.id,kind:'infrastructure',amount})}>Buy infrastructure</button><button onClick={()=>act('/economy/development','POST',{cityID:c.id,kind:'land',amount})}>Buy land</button></div><label>New improvement<select value={selected[c.id]||data.buildings[0]?.key} onChange={e=>setSelected({...selected,[c.id]:e.target.value})}>{Object.entries(groups).map(([category,items])=><optgroup label={category.toUpperCase()} key={category}>{items.map((b:any)=><option value={b.key} key={b.key}>{b.name} · {yen(b.cost)}{b.minTech?` · Tech ${b.minTech}`:''}</option>)}</optgroup>)}</select></label><button className="primary" disabled={c.used>=c.slots} onClick={()=>act('/economy/improvements','POST',{cityID:c.id,building:selected[c.id]||data.buildings[0]?.key})}><Plus size={15}/> Build improvement</button><details><summary>Auditable calculation</summary>{Object.entries(c.contributors).map(([k,v])=><div className="factor" key={k}><span>{k}</span><b>{Number(v).toFixed(4)}</b></div>)}<div className="factor"><span>Daily city tax</span><b>{yen(c.taxRevenue)}</b></div><div className="factor"><span>Daily upkeep</span><b>{yen(c.upkeep)}</b></div></details></section>)}</div>
    <section className="panel"><Landmark/><h2>National Happiness breakdown</h2>{Object.entries(r.contributors).map(([k,v])=><div className="factor" key={k}><span>{k}</span><b>{Number(v).toFixed(3)}</b></div>)}<h3>Daily resource production</h3><div className="resource-lines">{Object.entries(r.production).map(([k,v])=><Metric key={k} label={k} value={Number(v).toFixed(1)}/>)}</div></section>
  </div>
}

function Metric({label,value}:{label:string,value:string}){return <div><span>{label}</span><b>{value}</b></div>}
