import {useEffect,useState} from 'react';
import {Gem,LockKeyhole,Save} from 'lucide-react';
import './luxury-consumption.css';

const yen=(value:number)=>`¥${Math.round(value||0).toLocaleString()}`;

export default function LuxuryConsumptionPanel({data,onSaved}:{data:any;onSaved:()=>Promise<void>|void}){
 const[rate,setRate]=useState(Number(data?.dailyRate||0)),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 useEffect(()=>setRate(Number(data?.dailyRate||0)),[data?.dailyRate]);
 if(!data)return null;
 const save=async()=>{setSaving(true);setError('');try{const response=await fetch('/api/economy/luxury-consumption',{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({dailyRate:rate})}),body=await response.json();if(!response.ok)throw Error(body.error||'Unable to save Luxury Consumption.');await onSaved();window.dispatchEvent(new Event('diplomatia:resources'))}catch(e){setError((e as Error).message)}finally{setSaving(false)}};
 return <section className={'panel luxury-consumption '+(!data.unlocked?'locked':'')}><div className="luxury-heading"><div>{data.unlocked?<Gem/>:<LockKeyhole/>}<span className="eyebrow">LUXURY CONSUMPTION</span><h2>Domestic luxury market</h2></div><div><span>Size efficiency</span><b>{Number(data.sizeEfficiency).toFixed(2)}×</b><small>{yen(data.valuePerGood)} per Luxury Good</small></div></div>{!data.unlocked?<div className="luxury-project-gate"><b>{data.requiredProject} required</b><p>Luxury Goods remain untouched until this National Project is completed. They can still be stockpiled or traded.</p></div>:<><div className="luxury-stat-grid"><div><span>Available stockpile</span><b>{Number(data.stockpile).toLocaleString()} t</b></div><div><span>Maximum daily rate</span><b>{Number(data.maxRate).toFixed(1)} t</b></div><div><span>Today’s {data.settledToday?'actual':'projected'} consumption</span><b>{Number(data.projectedConsumption).toFixed(1)} t</b></div><div><span>Today’s {data.settledToday?'earned':'projected income'}</span><b>{yen(data.projectedIncome)}</b></div><div><span>Yesterday consumed</span><b>{Number(data.yesterdayConsumed).toFixed(1)} t</b></div><div><span>Yesterday earned</span><b>{yen(data.yesterdayIncome)}</b></div></div><label className="luxury-rate"><span>Desired daily consumption rate</span><div><input type="range" min="0" max={data.maxRate} step="0.1" value={Math.min(rate,Number(data.maxRate))} onChange={e=>setRate(Number(e.target.value))}/><input type="number" min="0" max={data.maxRate} step="0.1" value={rate} onChange={e=>setRate(Math.max(0,Number(e.target.value)||0))}/><b>t / day</b></div></label>{data.settledToday&&<small>Rate changes apply at the next UTC server-day settlement.</small>}{error&&<p className="error notice">{error}</p>}<button className="primary luxury-save" disabled={saving||rate>Number(data.maxRate)} onClick={save}><Save/>{saving?'Saving…':'Save consumption rate'}</button></>}</section>;
}
