import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{Shield,Landmark,GraduationCap,Heart,Microscope,ShoppingCart,Swords,LogOut,Clock,Users,Building2,BrainCircuit,Coins,Plus}from'lucide-react';import StrategicEconomyScreen from'./StrategicEconomyScreen';import RevenueScreen from'./RevenueScreen';import AllianceScreen from'./AllianceScreen';import SettingsScreen from'./SettingsScreen';import GameSidebar from'./GameSidebar';import HomeScreen from'./HomeScreen';import ResourceDock from'./ResourceDock';import{applyTheme}from'./theme';import'./styles.css';import'./features.css';import'./slots.css';import'./directory.css';import'./dark-theme.css';import'./population.css';import'./onboarding.css';import'./nation-types.css';import'./brand.css';import'./economy-v2.css';import'./navigation.css';import'./nav-groups.css';import'./projects.css';import'./resource-dock.css';import'./resource-icons.css';import'./alliances.css';import'./revenue.css';import'./strategy.css';import'./theme-controls.css';import'./light-theme.css';
import'./alliance-modern.css';
import'./gear-confirm.css';
import'./choice-details.css';
import NotificationsScreen from'./NotificationsScreen';
import MilitaryCommandScreen from'./MilitaryScreen';
import NationalProjectsScreen from'./NationalProjectsScreen';
import LeaderboardsScreen from'./LeaderboardsScreen';
import'./notifications.css';
import'./province-development.css';
import WorldLocationPicker,{type WorldLocation}from'./WorldLocationPicker';
import'./world-location.css';
import MarketScreen from'./MarketScreen';
import'./market-logistics.css';
import'./trade-confirm.css';
import'./trade-history.css';
import'./share-links.css';
import'./public-world-stats.css';
import'./province-roster.css';
import'./directory-pagination.css';
import'./footer-copyright.css';
const EconomyScreen=StrategicEconomyScreen;
function LegalModalHost(){const[legalDoc,setLegalDoc]=useState<{title:string;html:string}|null>(null),[loading,setLoading]=useState(false);useEffect(()=>{const open=async(e:MouseEvent)=>{const link=(e.target as HTMLElement).closest<HTMLAnchorElement>('a[href="/terms.html"],a[href="/privacy.html"]');if(!link)return;e.preventDefault();setLoading(true);try{const response=await fetch(link.getAttribute('href')!);if(!response.ok)throw Error();const parsed=new DOMParser().parseFromString(await response.text(),'text/html'),main=parsed.querySelector('main');setLegalDoc({title:link.getAttribute('href')==='/terms.html'?'Terms of Service':'Privacy Policy',html:main?.innerHTML||'<p>The document could not be loaded.</p>'})}catch{setLegalDoc({title:'Document unavailable',html:'<p>Please try again shortly.</p>'})}finally{setLoading(false)}};document.addEventListener('click',open);return()=>document.removeEventListener('click',open)},[]);useEffect(()=>{if(!legalDoc)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setLegalDoc(null)};window.addEventListener('keydown',close);const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{window.removeEventListener('keydown',close);document.body.style.overflow=previous}},[legalDoc]);if(!legalDoc&&!loading)return null;return <div className="legal-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setLegalDoc(null)}}><section className="legal-modal" role="dialog" aria-modal="true" aria-label={legalDoc?.title||'Loading legal document'}><header><div><span className="eyebrow">DIPLOMATIA</span><h2>{legalDoc?.title||'Loading…'}</h2></div><button type="button" autoFocus onClick={()=>setLegalDoc(null)} aria-label="Close legal document">×</button></header><div className="legal-modal-content">{legalDoc?<div dangerouslySetInnerHTML={{__html:legalDoc.html}}/>:<p>Loading document…</p>}</div><footer><button type="button" className="primary" onClick={()=>setLegalDoc(null)}>Close</button></footer></section></div>}
function GuardianIndicator({until,compact=false}:{until?:string;compact?:boolean}){const active=!!until&&new Date(until).getTime()>Date.now(),days=active?Math.max(1,Math.ceil((new Date(until!).getTime()-Date.now())/86400000)):0,expires=active?new Date(until!).toLocaleString():'';return <div className={'guardian '+(compact?'compact ':'')+(active?'':'expired')} tabIndex={0} aria-label={active?`Guardian status expires ${expires}`:'No active Guardian status'}><Shield size={compact?18:22}/><div><b>{active?'Guardian status':'Unprotected'}</b><span>{active?`${days} days remaining`:'Hostile actions permitted'}</span></div><span className="guardian-tooltip">{active?`Protected from hostile actions until ${expires}. Initiating a raid or war ends Guardian status early.`:'This nation currently has no active Guardian protection.'}</span></div>}
type MilitaryOverviewItem={key:string;name:string;quantity:number};type Nation={ID:string;Name:string;Motto:string;Currency:string;LeaderName:string;Government:string;Continent:string;UserType:'PLAYER'|'DEV'|'BOT';Treasury:number;Coal:number;Steel:number;Food:number;Population:number;Happiness:number;Education:number;Technology:number;QOL:number;GuardianUntil?:string;LocationLat?:number|null;LocationLng?:number|null;Military?:MilitaryOverviewItem[]};type City={id:string;name:string;level:number;totalInvested:number;improvementSlots:number;usedSlots:number;populationCapacity:number;nextExpansionCost:number;industries:string};const money=(n:number)=>`¥${n.toLocaleString()}`;const api=async(path:string,options?:RequestInit)=>{let r:Response;try{r=await fetch('/api'+path,{credentials:'include',headers:{'Content-Type':'application/json'},...options})}catch{throw Error('Unable to reach the Diplomatia server. Please try again shortly.')}const text=r.status===204?'':await r.text();let v:any=null;if(text){try{v=JSON.parse(text)}catch{if(r.status===502||r.status===503||r.status===504)throw Error('The Diplomatia API is temporarily unavailable. Check the backend deployment and try again.');throw Error(`The server returned an invalid response (HTTP ${r.status}).`)}}if(!r.ok)throw Error(v?.error||`Request failed (HTTP ${r.status}).`);return v};
const governments=['Parliamentary Democracy','Presidential Republic','Federal Republic','Constitutional Monarchy','Absolute Monarchy','One-Party State','Military Junta','Theocracy'];const continentOptions=['Africa','Asia','Europe','North America','South America','Oceania','Antarctica'];
const tabPaths:Record<string,string>={home:'/home',overview:'/nation/me',nations:'/nations','alliance-list':'/alliances',leaderboards:'/leaderboards','my-alliance':'/alliance/me',revenue:'/revenue',notifications:'/notifications',profile:'/nation/edit',settings:'/settings',economy:'/economy','national-projects':'/national-projects',market:'/market',military:'/military'};
type AppRoute={tab:string;nationID?:string;allianceID?:string;shipmentID?:string;marketView?:'public'|'mine'|'direct'|'shipments';valid:boolean};
function readRoute():AppRoute{const path=decodeURIComponent(location.pathname).replace(/\/+$/,'')||'/';if(path==='/')return{tab:'home',valid:true};for(const[tab,target]of Object.entries(tabPaths))if(path===target)return{tab,valid:true};let match=path.match(/^\/nation\/([^/]+)$/);if(match&&match[1]!=='me'&&match[1]!=='edit')return{tab:'nations',nationID:match[1],valid:true};match=path.match(/^\/alliance\/([^/]+)$/);if(match&&match[1]!=='me')return{tab:'alliance-list',allianceID:match[1],valid:true};match=path.match(/^\/market\/shipment\/([^/]+)$/);if(match)return{tab:'market',shipmentID:match[1],marketView:'shipments',valid:true};match=path.match(/^\/market\/(public|mine|direct|shipments)$/);if(match)return{tab:'market',marketView:match[1] as AppRoute['marketView'],valid:true};return{tab:'not-found',valid:false}}
function navigateTo(path:string,replace=false){history[replace?'replaceState':'pushState'](null,'',path);window.dispatchEvent(new PopStateEvent('popstate'))}
function App(){const[me,setMe]=useState<{user:{Email:string;ThemePreference:'dark'|'light'};nation:Nation|null}|null>(null),[error,setError]=useState(''),[route,setRoute]=useState<AppRoute>(readRoute);const load=()=>api('/me').then(setMe).catch(()=>setMe(null));useEffect(()=>{void load();const update=()=>setRoute(readRoute());window.addEventListener('popstate',update);return()=>window.removeEventListener('popstate',update)},[]);useEffect(()=>{if(me?.user.ThemePreference)applyTheme(me.user.ThemePreference)},[me]);if(!me)return <Auth onDone={load} error={error} setError={setError}/>;if(!me.nation)return <FoundNation onDone={load}/>;const n=me.nation,tab=route.tab,days=n.GuardianUntil?Math.max(0,Math.ceil((new Date(n.GuardianUntil).getTime()-Date.now())/86400000)):0,logout=()=>{void api('/auth/logout',{method:'POST'}).then(()=>setMe(null))},setTab=(next:string)=>navigateTo(tabPaths[next]||'/home');return <div className="shell"><GameSidebar tab={tab} setTab={setTab} logout={logout}/><main><header><div><span className="eyebrow">{n.Government} · {n.Continent}</span><h1>{n.Name}</h1><p>{n.Motto||`Led by ${n.LeaderName}`}</p></div><GuardianIndicator until={n.GuardianUntil}/></header><ResourceDock/>{!route.valid?<RouteNotFound/>:tab==='home'?<HomeScreen/>:tab==='overview'?<Overview n={n}/>:tab==='nations'?<NationDirectory nationID={route.nationID}/>:tab==='alliance-list'?<AllianceScreen mode="directory" allianceID={route.allianceID}/>:tab==='leaderboards'?<LeaderboardsScreen/>:tab==='my-alliance'?<AllianceScreen mode="mine"/>:tab==='revenue'?<RevenueScreen/>:tab==='notifications'?<NotificationsScreen/>:tab==='profile'?<NationEditor n={n} reload={load}/>:tab==='settings'?<SettingsScreen/>:tab==='economy'?<EconomyScreen/>:tab==='national-projects'?<NationalProjectsScreen/>:tab==='technology'?<Technology reload={load}/>:tab==='market'?<MarketScreen shipmentID={route.shipmentID} initialView={route.marketView}/>:tab==='military'?<Military protected={!!days}/>:null}<WorldFooter/></main></div>}
function RouteNotFound(){return <section className="panel wide"><span className="eyebrow">404 · UNKNOWN DESTINATION</span><h2>This Diplomatia link does not exist.</h2><p>The page may have moved or the shared link may be incomplete.</p><button className="primary" onClick={()=>navigateTo('/home')}>Return to World Home</button></section>}
function ShareableIdentity({kind,id,name}:{kind:'nation'|'alliance';id:string;name:string}){const[copied,setCopied]=useState(false),path=`/${kind}/${encodeURIComponent(id)}`,url=location.origin+path;const copy=async()=>{try{await navigator.clipboard.writeText(url);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{setCopied(false)}};return <section className="share-identity"><div><span>{kind} ID</span><code>{id}</code></div><div><span>Shareable {kind} link</span><a href={path} onClick={e=>{e.preventDefault();navigateTo(path)}}>{url}</a></div><button onClick={copy} aria-label={`Copy ${name} link`}>{copied?'Copied':'Copy link'}</button></section>}
function Auth({onDone,error,setError}:{onDone:()=>void,error:string;setError:(v:string)=>void}){const[register,setRegister]=useState(true);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/auth/'+(register?'register':'login'),{method:'POST',body:JSON.stringify({email:f.get('email'),password:f.get('password')})});onDone()}catch(x){setError((x as Error).message)}}return <div className="gate"><section><div className="brand light"><div className="crest">D</div><b>Diplomatia</b></div><span className="kicker">A persistent geopolitical strategy game</span><h1>Build a nation<br/>worth defending.</h1><p>Create your account, found your nation, then shape Provinces, markets, Alliances, and diplomacy.</p><PublicWorldStats/><div className="feature"><Shield/><span><b>30 days of Guardian status</b><small>Build in peace. Protection ends if you initiate a raid or war.</small></span></div></section><form onSubmit={submit}><div className="onboarding-steps"><b className="current">1</b><span>Account</span><i/><b>2</b><span>Nation</span><i/><b>3</b><span>Play</span></div><span className="eyebrow">{register?'STEP 1 · CREATE ACCOUNT':'RETURN TO COMMAND'}</span><h2>{register?'Create your account':'Welcome back'}</h2><label>Email<input name="email" type="email" inputMode="email" autoComplete="email" maxLength={320} required/></label><label>Password<input name="password" type="password" autoComplete={register?'new-password':'current-password'} minLength={10} maxLength={72} required/></label>{error&&<p className="error">{error}</p>}<button className="primary">{register?'Continue to nation creation':'Enter command center'}</button>{register&&<p className="legal-consent">By creating an account, you agree to Diplomatia’s <a href="/terms.html" target="_blank">Terms of Service</a> and acknowledge the <a href="/privacy.html" target="_blank">Privacy Policy</a>.</p>}<button type="button" className="link" onClick={()=>setRegister(!register)}>{register?'Already registered? Sign in':'New player? Register'}</button></form></div>}
function PublicWorldStats(){const[data,setData]=useState<any>();useEffect(()=>{void fetch('/api/world/stats').then(r=>r.ok?r.json():null).then(setData)},[]);if(!data)return null;const stats=[['Nations',data.nations],['Provinces',data.cities],['Population',data.population],['Alliances',data.alliances],['Open offers',data.openMarketOrders],['Trades conducted',data.totalTrades],['Delivered',data.completedTrades],['In transit',data.activeShipments],['Delayed',data.delayedTrades],['Active now',data.activePlayers],['Active 24h',data.activePlayers24Hours]];return <div className="public-world-stats">{stats.map(([label,value])=><div key={label}><b>{Number(value).toLocaleString()}</b><span>{label}</span></div>)}</div>}
function FoundNation({onDone}:{onDone:()=>void}){const[error,setError]=useState(''),[busy,setBusy]=useState(false),[location,setLocation]=useState<WorldLocation|null>(null);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');if(!location){setError('Choose a valid land position for your nation.');return}setBusy(true);const f=new FormData(e.currentTarget);try{await api('/nations',{method:'POST',body:JSON.stringify({...Object.fromEntries(f),latitude:location.latitude,longitude:location.longitude})});await onDone()}catch(x){setError((x as Error).message);setBusy(false)}}return <div className="found"><form onSubmit={submit}><div className="onboarding-steps"><b>✓</b><span>Account</span><i/><b className="current">2</b><span>Nation</span><i/><b>3</b><span>Play</span></div><span className="eyebrow">STEP 2 · CREATE NATION</span><h1>Found your nation</h1><p>Choose your public identity, establish your capital, and place it on the map. Your nation enters the world with 30 days of Guardian status.</p><div className="form-pair"><label>Leader name<input name="leaderName" minLength={2} maxLength={100} required/></label><label>Nation name<input name="name" minLength={3} maxLength={100} required/></label></div><label>Capital Province<input name="capital" minLength={2} maxLength={100} required/></label><label>Government<select name="government" required>{governments.map(x=><option key={x}>{x}</option>)}</select></label><WorldLocationPicker value={location} onChange={setLocation} disabled={busy}/>{error&&<p className="error notice">{error}</p>}<button className="primary" disabled={busy}>{busy?'Founding nation…':'Found nation and play'}</button></form></div>}
function Overview({n}:{n:Nation}){const a=n as Nation&{AllianceID?:string;AllianceName?:string;CreatedAt:string;EmploymentRate:number;TaxRate:number;ProvinceCount:number;EconomicGear:string},indicators=[['Citizen satisfaction',`${n.Happiness.toFixed(0)}%`,'Directly affects population growth and citizen income.'],['Education',`${n.Education.toFixed(0)}%`,'Improves productivity, effective population, and economic output.'],['Employment rate',`${Number(a.EmploymentRate).toFixed(1)}%`,'Determines how much of the population contributes to cash income.'],['Population',n.Population.toLocaleString(),'The effective population supporting the national tax base.'],['Provinces',a.ProvinceCount.toLocaleString(),'Geographic and economic units generating national output.'],['Economic Gear',gearLabel(a.EconomicGear),'The current national economic focus and its strategic multipliers.']] as const;return <><section className="panel nation-alliance-summary"><div><span className="eyebrow">ALLIANCE AFFILIATION</span><h2>{a.AllianceName||'Independent nation'}</h2>{a.AllianceID?<AllianceLink allianceID={a.AllianceID} mine>View My Alliance</AllianceLink>:<AllianceLink>Browse Alliances</AllianceLink>}</div><div className="nation-founded"><span>Nation founded</span><b>{nationFoundedLabel(a.CreatedAt)}</b></div></section><div className="grid nation-overview-grid"><section className="panel"><span className="eyebrow">NATIONAL INDICATORS</span><h2>Current national conditions</h2><div className="current-indicators">{indicators.map(([label,value,description])=><article key={label}><span>{label}</span><b>{value}</b><small>{description}</small></article>)}</div></section><MilitaryUnitOverview units={n.Military}/></div><NationLocationMap latitude={n.LocationLat} longitude={n.LocationLng} continent={n.Continent}/><NationTradeHistory nationID={n.ID} nationName={n.Name}/></>}
function Resource({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value}</b></div>}
function MilitaryUnitOverview({units}:{units?:MilitaryOverviewItem[]}){const defaults=[['soldiers','Soldiers'],['tanks','Tanks'],['ships','Ships'],['jets','Fighter Jets'],['drones','Drones']],byKey=new Map((units||[]).map(unit=>[unit.key,unit]));return <section className="panel nation-military-overview"><div className="military-overview-heading"><div><span className="eyebrow">MILITARY OVERVIEW</span><h2>Armed Forces</h2></div><Swords/></div><div className="military-unit-strip">{defaults.map(([key,name])=>{const unit=byKey.get(key);return <article key={key}><span>{name}</span><b>{Number(unit?.quantity||0).toLocaleString()}</b></article>})}</div></section>}
function nationFoundedLabel(raw:string){const founded=new Date(raw),days=Math.max(0,Math.floor((Date.now()-founded.getTime())/86400000)),age=days<365?`${days} ${days===1?'day':'days'} old`:`${Math.floor(days/365)} ${Math.floor(days/365)===1?'year':'years'} old`;return `${founded.toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'})} · ${age}`}
function gearLabel(key:string){return({balanced:'Balanced / Mixed',agrarian:'Agrarian / Expansionist',industrial:'Industrial',commercial:'Commercial / Trade',militarized:'Militarized Economy'} as Record<string,string>)[key]||'Balanced / Mixed'}
function provinceSpecializationLabel(key:string){return({mixed:'Mixed',agriculture:'Agriculture',extraction:'Extraction',industry:'Industry',commerce:'Commerce',military:'Military'} as Record<string,string>)[key]||key}
function NationDirectory({nationID}:{nationID?:string}){
 const[q,setQ]=useState(''),[items,setItems]=useState<any[]>([]),[selected,setSelected]=useState<any>(),[error,setError]=useState(''),[page,setPage]=useState(1),pageSize=10;
 useEffect(()=>{const timer=setTimeout(()=>api('/nations?search='+encodeURIComponent(q)).then(result=>{setItems(result);setPage(1)}),250);return()=>clearTimeout(timer)},[q]);
 useEffect(()=>{if(!nationID){setSelected(undefined);setError('');return}setSelected(undefined);api('/nations/'+encodeURIComponent(nationID)).then(setSelected).catch(e=>setError((e as Error).message))},[nationID]);
 if(nationID){if(error)return <section className="panel wide"><button className="back" onClick={()=>navigateTo('/nations')}>← All nations</button><h2>Nation not found</h2><p>{error}</p></section>;if(!selected)return <section className="panel wide">Loading nation…</section>;return <NationView nation={selected} close={()=>navigateTo('/nations')}/>}
 const pages=Math.max(1,Math.ceil(items.length/pageSize)),visible=items.slice((page-1)*pageSize,page*pageSize);
 return <><section className="section-intro"><span className="eyebrow">WORLD DIRECTORY · SORTED BY POPULATION</span><h2>Registered nations</h2><input className="nation-search" type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search nations, leaders, or Alliances…"/></section><div className="directory-grid">{visible.map(n=><button className="nation-card" key={n.id} onClick={()=>navigateTo('/nation/'+encodeURIComponent(n.id))}><div className="card-meta"><span className="eyebrow">{n.continent}</span><TypeBadge type={n.userType}/></div><h3>{n.name}</h3><p>{n.government}</p><div className="nation-population"><span>Population</span><b>{Number(n.population).toLocaleString()}</b></div><div className={'nation-alliance '+(n.allianceName?'affiliated':'independent')}>{n.allianceName||'Independent nation'}</div><small>Leader {n.leaderName} · {n.cityCount} {n.cityCount===1?'Province':'Provinces'}</small></button>)}</div><DirectoryPager page={page} pages={pages} total={items.length} setPage={setPage}/></>
}
function DirectoryPager({page,pages,total,setPage}:{page:number;pages:number;total:number;setPage:(page:number)=>void}){if(pages<=1)return null;return <nav className="directory-pager" aria-label="Directory pages"><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} of {pages} · {total} results</span><button disabled={page===pages} onClick={()=>setPage(page+1)}>Next</button></nav>}
function NationView({nation:n,close}:{nation:any;close:()=>void}){return <section className="panel nation-view"><button className="back" onClick={close}>← All nations</button><div className="card-meta"><span className="eyebrow">{n.continent} · FOUNDED {nationFoundedLabel(n.createdAt)}</span><TypeBadge type={n.userType}/></div><div className="nation-title-row"><div><h2>{n.name}</h2><p className="motto">{n.motto||'No national motto has been declared.'}</p></div><GuardianIndicator until={n.guardianUntil} compact/></div><div className="profile-facts"><Resource label="User type" value={n.userType}/><Resource label="Last active" value={relativeActivity(n.lastActiveAt)}/><Resource label="Population" value={Number(n.population).toLocaleString()}/><Resource label="Leader" value={n.leaderName}/><Resource label="Government" value={n.government}/><div><span>Alliance</span>{n.allianceID?<AllianceLink allianceID={n.allianceID}>{n.allianceName}</AllianceLink>:<AllianceLink>Independent · Browse Alliances</AllianceLink>}</div><Resource label="Capital Province" value={n.capital}/><Resource label="Provinces" value={String(n.cityCount)}/></div><section className="public-economy"><div className="economic-focus"><span className="eyebrow">ECONOMIC FOCUS</span><h3>{gearLabel(n.economicGear)}</h3></div><div><span className="eyebrow">PROVINCE SETUP</span><div className="public-provinces">{n.provinceSetup?.map((p:any)=><article key={p.name}><b>{p.name}</b><span>{provinceSpecializationLabel(p.specialization)}</span><small>{Math.round(p.infrastructure)} Infrastructure</small></article>)}</div></div></section><MilitaryUnitOverview units={n.military}/><NationLocationMap latitude={n.locationLat} longitude={n.locationLng} continent={n.continent}/><NationTradeHistory nationID={n.id} nationName={n.name}/><p className="privacy-note">Economic resources, treasury, deposits, production totals, and internal indicators are private.</p></section>}
function NationLocationMap({latitude,longitude,continent}:{latitude?:number|null;longitude?:number|null;continent:string}){if(latitude==null||longitude==null)return <section className="panel location-unset"><span className="eyebrow">NATIONAL LOCATION</span><h3>{continent}</h3><p>This nation has not selected its precise map position yet.</p></section>;return <WorldLocationPicker value={{latitude:Number(latitude),longitude:Number(longitude),continent}} onChange={()=>{}} readOnly compact/>}
function NationTradeHistory({nationID,nationName}:{nationID:string;nationName:string}){
 const[open,setOpen]=useState(false),[data,setData]=useState<any>(),[error,setError]=useState('');
 const show=()=>{setOpen(true);setError('');api(`/nations/${nationID}/trades`).then(setData).catch(e=>setError((e as Error).message))};
 useEffect(()=>{if(!open)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[open]);
 return <><ShareableIdentity kind="nation" id={nationID} name={nationName}/><button className="trade-history-button" onClick={show}><ShoppingCart size={16}/>View trading history</button>{open&&<div className="trade-history-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="trade-history-modal" role="dialog" aria-modal="true" aria-label={`${nationName} trading history`}><header><div><span className="eyebrow">PUBLIC COMMERCE LOG</span><h2>{nationName} trading history</h2></div><button className="modal-close" onClick={()=>setOpen(false)} aria-label="Close trade history">×</button></header><div className="trade-history-content">{error?<p className="error notice">{error}</p>:!data?<p>Loading trade history…</p>:data.items.length?<><div className="trade-history-head"><span>Direction</span><span>Trade</span><span>Partner</span><span>Value</span><span>Status</span><span>Date</span></div>{data.items.map((item:any)=><div className="trade-history-row" key={item.id}><span className={'trade-direction '+item.direction}>{item.direction}</span><b>{Number(item.quantity).toLocaleString(undefined,{maximumFractionDigits:3})} {String(item.resource).replaceAll('_',' ')}</b><span>{item.partner}</span><span>{money(Number(item.goodsValue))}</span><span className={'history-status '+item.status}>{String(item.status).replace('_',' ')}</span><time title={new Date(item.departedAt).toLocaleString()}>{item.deliveredAt?new Date(item.deliveredAt).toLocaleDateString():new Date(item.departedAt).toLocaleDateString()}</time></div>)}</>:<div className="trade-history-empty">No accepted trades have been recorded for this nation.</div>}</div></section></div>}</>
}
function relativeActivity(raw?:string){if(!raw)return 'No recorded activity';const seconds=Math.max(0,Math.floor((Date.now()-new Date(raw).getTime())/1000));if(seconds<60)return 'Less than a minute ago';const minutes=Math.floor(seconds/60);if(minutes<60)return `${minutes} ${minutes===1?'minute':'minutes'} ago`;const hours=Math.floor(minutes/60);if(hours<24)return `${hours} ${hours===1?'hour':'hours'} ago`;const days=Math.floor(hours/24);return `${days} ${days===1?'day':'days'} ago`}
function AllianceLink({allianceID,mine=false,children}:{allianceID?:string;mine?:boolean;children:React.ReactNode}){const path=allianceID?`/alliance/${encodeURIComponent(allianceID)}`:mine?'/alliance/me':'/alliances';return <a className="alliance-profile-link" href={path} onClick={e=>{e.preventDefault();navigateTo(path)}}>{children} →</a>}
function TypeBadge({type}:{type:string}){return <span className={'type-badge '+type.toLowerCase()}>{type}</span>}
function NationEditor({n,reload}:{n:Nation;reload:()=>void}){const[form,setForm]=useState({motto:n.Motto,government:n.Government}),[message,setMessage]=useState('');const field=(key:string,value:string)=>setForm({...form,[key]:value});const save=async()=>{try{await api('/nation/settings',{method:'PATCH',body:JSON.stringify(form)});setMessage('Nation profile saved.');reload()}catch(e){setMessage((e as Error).message)}};return <section className="panel profile-editor"><span className="eyebrow">NATION PROFILE</span><h2>Edit public details</h2><p>Your nation and leader names are permanent for now. A formal name-change path will be added later.</p><div className="profile-facts"><Resource label="Nation name" value={n.Name}/><Resource label="Leader name" value={n.LeaderName}/><Resource label="Continent" value={n.Continent}/></div><label>National motto<input value={form.motto} maxLength={120} onChange={e=>field('motto',e.target.value)}/></label><label>Government<select value={form.government} onChange={e=>field('government',e.target.value)}>{governments.map(x=><option key={x}>{x}</option>)}</select></label>{message&&<p>{message}</p>}<button className="primary" onClick={save}>Save nation profile</button><NationLocationReset nation={n} reload={reload}/></section>}
function NationLocationReset({nation,reload}:{nation:Nation;reload:()=>void}){const hasLocation=nation.LocationLat!=null&&nation.LocationLng!=null,current=hasLocation?{latitude:Number(nation.LocationLat),longitude:Number(nation.LocationLng),continent:nation.Continent}:null,[location,setLocation]=useState<WorldLocation|null>(current),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const changed=!!location&&(!current||location.latitude!==current.latitude||location.longitude!==current.longitude);const reset=async()=>{if(!location)return;setBusy(true);setMessage('');try{const result=await api('/nation/location',{method:'POST',body:JSON.stringify({latitude:location.latitude,longitude:location.longitude})});setMessage(result.cost?`Location reset to ${result.continent}. ¥${Number(result.cost).toLocaleString()} was deducted.`:`Initial location saved in ${result.continent} at no cost.`);setConfirm(false);await reload()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};return <div className="location-reset"><span className="eyebrow">LOCATION CONTROL</span><h3>{hasLocation?'Reset national location':'Set initial national location'}</h3><p>{hasLocation?'Relocating changes your continent and costs ¥5,000,000. This has no cooldown yet, but every confirmed reset is charged.':'This nation predates map locations. Your first placement is free; future resets cost ¥5,000,000.'}</p><WorldLocationPicker value={location} onChange={value=>{setLocation(value);setConfirm(false)}} disabled={busy}/>{confirm?<div className="reset-warning"><p><b>Confirm relocation to {location?.continent}?</b> {hasLocation?'¥5,000,000 will be deducted immediately.':'This initial placement is free.'}</p><div className="location-reset-actions"><button className="primary danger-action" disabled={busy} onClick={reset}>{busy?'Saving…':'Confirm location change'}</button><button disabled={busy} onClick={()=>setConfirm(false)}>Cancel</button></div></div>:<button disabled={!changed||busy} onClick={()=>setConfirm(true)}>{hasLocation?'Review ¥5,000,000 location reset':'Review free initial placement'}</button>}{message&&<p className="notice">{message}</p>}</div>}
function Cities({reload:_reload}:{reload:()=>void}){return <EconomyScreen/>}
function CityCard({city,act}:{city:City;act:(p:string,b:object)=>void}){const[next,setNext]=useState('transit'),full=city.usedSlots>=city.improvementSlots;return <section className="panel city-card"><div className="city-title"><Building2/><div><span className="eyebrow">CITY LEVEL {city.level}</span><h2>{city.name}</h2></div></div><div className="slot-line"><b>{city.usedSlots} / {city.improvementSlots} improvement slots used</b><div className="progress"><i style={{width:(city.usedSlots/city.improvementSlots*100)+'%'}}/></div></div><p>{money(city.totalInvested)} committed to long-term development.</p><button className="expand" disabled={city.improvementSlots>=12} onClick={()=>act('/cities/expand',{cityID:city.id})}>Add one improvement slot · {money(city.nextExpansionCost)}</button><label>Municipal improvement<select value={next} onChange={e=>setNext(e.target.value)}><option value="transit">Public transit</option><option value="housing">Housing expansion</option><option value="healthcare">Healthcare network</option><option value="schools">Schools and universities</option><option value="commercial">Commercial districts</option></select></label><button className="primary" disabled={full} onClick={()=>act('/cities/invest',{cityID:city.id,program:next})}>{full?'No open slots':`Build improvement · ${money(1000000*(city.usedSlots+1)*(city.usedSlots+1))}`}</button><div className="industry"><b>Resource improvements</b>{[['food',2],['coal',3],['steel',5]].map(([r,l])=><button disabled={full||city.level<Number(l)} onClick={()=>act('/cities/industry',{cityID:city.id,resource:r})} key={r}>{String(r)} {city.level<Number(l)?`· unlocks level ${l}`:'· uses one slot'}</button>)}</div></section>}
function Technology({_reload}:{_reload?:()=>void;reload?:()=>void}){return null}
function Income(){return <EconomyScreen/>}
function Factor({label,value}:{label:string;value:number}){return <div className="factor"><span>{label}</span><b>× {value.toFixed(3)}</b></div>}
function WorldFooter(){const[s,setS]=useState<any>(),[,setTick]=useState(0);useEffect(()=>{void api('/world/status').then(setS);const i=setInterval(()=>setTick(x=>x+1),1000),j=setInterval(()=>api('/world/status').then(setS),60000);return()=>{clearInterval(i);clearInterval(j)}},[]);if(!s)return null;const elapsed=Date.now()-new Date(s.realTime).getTime(),real=new Date(new Date(s.realTime).getTime()+elapsed),game=new Date(new Date(s.gameTime).getTime()+elapsed*s.gameSpeed);return <footer><div className="footer-clocks"><span><Clock size={15}/> Real {real.toLocaleString()}</span><span><Clock size={15}/> Game {game.toLocaleString()} · {s.gameSpeed}×</span><small className="footer-copyright">© {new Date().getFullYear()} Diplomatia. All rights reserved.</small></div><span className="legal-links"><a href="/terms.html" target="_blank">Terms</a><a href="/privacy.html" target="_blank">Privacy</a></span><div className="online"><span><Users size={15}/><i/> {s.activePlayers} active in the last 5 minutes</span><span className="daily-active"><Users size={15}/>{s.activePlayers24Hours} active in the last 24 hours</span></div></footer>}
function Military(_props:{protected:boolean}){return <MilitaryCommandScreen/>}
function Empty({title,text}:{title:string;text:string}){return <section className="panel wide"><span className="eyebrow">COMING NEXT</span><h2>{title}</h2><p>{text}</p></section>}createRoot(document.getElementById('root')!).render(<><LegalModalHost/><App/></>);
