import {useEffect,useState}from'react';
import './shipment-layout.css';
import MaritimeTradeRouteMap from './MaritimeTradeRouteMap';
import{ArrowRight,Clock,Globe2,PackageCheck,Plus,RefreshCw,Search,Ship,Users}from'lucide-react';

const request=async(path:string,options?:RequestInit)=>{const response=await fetch('/api'+path,{credentials:'include',headers:{'Content-Type':'application/json'},...options}),text=await response.text();let data:any={};try{data=text?JSON.parse(text):{}}catch{throw Error(`Invalid server response (${response.status}).`)}if(!response.ok)throw Error(data.error||'Request failed.');if(path==='/market/orders'&&options?.method==='POST'){if(data?.marketVersion!==2||!data?.orderID)throw Error('The API did not confirm escrow. Redeploy the Diplomatia API and try again.');window.dispatchEvent(new Event('diplomatia:resources'))}return data};
const labels:Record<string,string>={foodstuffs:'Foodstuffs',timber:'Timber',fibers:'Fibers',basic_metals:'Basic Metals',energy:'Energy',strategic_minerals:'Strategic Minerals',textiles:'Textiles',processed_foods:'Processed Foods',construction_materials:'Construction Materials',basic_goods:'Basic Goods',consumer_goods:'Consumer Goods',military_equipment:'Military Equipment',luxury_goods:'Luxury Goods',tanks:'Tanks',ships:'Ships',jets:'Fighter Jets',drones:'Drones'};
const commodityKeys=Object.keys(labels);
const yen=(amount:number)=>`¥${Number(amount).toLocaleString()}`;
const quantity=(amount:number)=>Number(amount).toLocaleString(undefined,{maximumFractionDigits:3});

const go=(path:string)=>{history.pushState(null,'',path);window.dispatchEvent(new PopStateEvent('popstate'))};
export default function MarketScreen({shipmentID,initialView}:{shipmentID?:string;initialView?:'public'|'mine'|'direct'|'shipments'}){
 const[data,setData]=useState<any>({offers:[],shipments:[],commodities:[]}),[tab,setTab]=useState<'public'|'mine'|'direct'|'shipments'>(initialView||'public'),[creating,setCreating]=useState(false),[selected,setSelected]=useState<any>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{try{setError('');const next=await request('/market');if(next?.marketVersion!==2||!Array.isArray(next.offers)||!Array.isArray(next.shipments))throw Error('This frontend is connected to an outdated Diplomatia API. Redeploy the API service before posting trades.');setData(next);if(next.warning)setError(String(next.warning));if(shipmentID){const found=next.shipments.find((x:any)=>x.id===shipmentID);if(found){setSelected(found);setTab('shipments')}else setError('That shipment does not exist or is not visible to your nation.')}}catch(e){setError((e as Error).message)}};
 useEffect(()=>{void load();const timer=setInterval(load,60000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{setTab(initialView||'public');if(!shipmentID)setSelected(undefined);void load()},[shipmentID,initialView]);
 useEffect(()=>{if(shipmentID)return;const path=tab==='public'?'/market':`/market/${tab}`;if(location.pathname!==path)history.replaceState(null,'',path)},[tab,shipmentID]);
 const act=async(path:string)=>{setBusy(true);try{const result=await request(path,{method:'POST'});window.dispatchEvent(new Event('diplomatia:resources'));await load();if(result.shipmentID){setTab('shipments');const shipments=(await request('/market')).shipments;setData((d:any)=>({...d,shipments}));setSelected(shipments.find((x:any)=>x.id===result.shipmentID))}}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const offers=(Array.isArray(data.offers)?data.offers:[]).filter((offer:any)=>tab==='mine'?Boolean(offer.isMine):tab==='public'?String(offer.status).toLowerCase()==='open'&&String(offer.channel||'public').trim().toLowerCase()!=='private':String(offer.channel).trim().toLowerCase()==='private');
 return <div className="trade-page"><section className="trade-hero"><div><span className="eyebrow">GLOBAL LOGISTICS NETWORK</span><h2>World Market</h2><p>Every trade is escrowed, shipped across the map, and delivered on an hourly turn. Regional commerce arrives faster and costs less.</p></div><Globe2/></section><nav className="trade-tabs"><button className={tab==='public'?'active':''} onClick={()=>{setTab('public');setSelected(undefined)}}><Search/>Public Market</button><button className={tab==='mine'?'active':''} onClick={()=>{setTab('mine');setCreating(false);setSelected(undefined)}}><PackageCheck/>My Open Offers</button><button className={tab==='direct'?'active':''} onClick={()=>{setTab('direct');setSelected(undefined)}}><Users/>Direct Trades</button><button className={tab==='shipments'?'active':''} onClick={()=>setTab('shipments')}><Ship/>Shipments <b>{data.shipments.filter((x:any)=>x.status!=='delivered').length}</b></button><button className="refresh" onClick={load} aria-label="Refresh market"><RefreshCw/></button></nav>{error&&<p className="error notice">{error}</p>}{tab!=='shipments'&&<><div className="trade-actions"><div><h3>{tab==='public'?'Open offers':tab==='mine'?'My open offers':'Private contracts'}</h3><p>{tab==='public'?'Accept a public price or publish your own.':tab==='mine'?'Review or cancel any unaccepted offer and immediately return its escrow.':'Only the named trade partner can accept or decline a direct offer.'}</p></div>{tab!=='mine'&&<button className="primary" onClick={()=>setCreating(!creating)}><Plus/>New {tab==='public'?'market offer':'direct trade'}</button>}</div>{creating&&tab!=='mine'&&<TradeForm channel={tab==='public'?'public':'private'} commodities={Array.isArray(data.commodities)&&data.commodities.length?data.commodities:commodityKeys} close={()=>setCreating(false)} saved={async()=>{setCreating(false);await load()}}/>}<div className="offer-list">{offers.length?offers.map((offer:any)=><OfferCard key={offer.id} offer={offer} busy={busy} accept={()=>act(`/market/orders/${offer.id}/accept`)} cancel={()=>act(`/market/orders/${offer.id}/cancel`)} reject={()=>act(`/market/orders/${offer.id}/reject`)}/>):<section className="panel trade-empty"><PackageCheck/><h3>{tab==='mine'?'You have no open offers':`No ${tab==='public'?'public offers':'direct contracts'} available`}</h3><p>{tab==='mine'?'Published public and direct offers will remain here until accepted, declined, or cancelled.':'Create the first offer in this channel.'}</p></section>}</div></>}{tab==='shipments'&&<ShipmentArea shipments={data.shipments} selected={selected} setSelected={setSelected}/>}</div>
}

function TradeForm({channel,commodities,close,saved}:{channel:string;commodities:string[];close:()=>void;saved:()=>Promise<void>}){const[busy,setBusy]=useState(false),[error,setError]=useState(''),[review,setReview]=useState<any>();const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');const form=Object.fromEntries(new FormData(e.currentTarget));if(channel==='private'&&!review){setReview(form);return}setBusy(true);try{await request('/market/orders',{method:'POST',body:JSON.stringify({...form,channel,quantity:Number(form.quantity),unitPrice:Number(form.unitPrice)})});await saved()}catch(x){setError((x as Error).message);setBusy(false)}};return <form className="panel trade-form" onSubmit={submit} onChange={()=>setReview(undefined)}><div><span className="eyebrow">ESCROWED OFFER</span><h3>{channel==='public'?'Publish to the world':'Propose private terms'}</h3></div>{channel==='private'&&<label>Trade partner nation<input name="targetNationName" minLength={3} maxLength={100} placeholder="Enter the exact nation name" autoComplete="off" required/><small>Nation names are unique. The server verifies the exact name before creating the contract.</small></label>}<div className="trade-form-grid"><label>Offer type<select name="side"><option value="sell">Sell my goods</option><option value="buy">Buy their goods</option></select></label><label>Commodity<select name="resource">{commodities.map(x=><option value={x} key={x}>{labels[x]||x}</option>)}</select></label><label>Quantity<input name="quantity" type="number" min="0.001" max="1000000000" step="0.001" required/></label><label>Price per unit<input name="unitPrice" type="number" min="1" step="1" required/></label></div><p className="escrow-note">Sell offers immediately lock the listed goods. Buy offers immediately lock the full purchase price. Shipping is calculated when a partner accepts.</p>{review&&<div className="trade-review"><span className="eyebrow">CONFIRM DIRECT CONTRACT</span><h4>Send this offer to {String(review.targetNationName)}?</h4><p>{review.side==='sell'?'Offer to sell':'Request to buy'} {quantity(Number(review.quantity))} {labels[String(review.resource)]||String(review.resource)} at {yen(Number(review.unitPrice))} per unit. The named nation must accept before shipment.</p></div>}{error&&<p className="error">{error}</p>}<div className="form-buttons"><button className="primary" disabled={busy}>{busy?'Locking escrow…':channel==='private'?(review?'Confirm, escrow, and send':'Review direct trade'):'Publish and escrow'}</button>{review&&<button type="button" onClick={()=>setReview(undefined)}>Edit terms</button>}<button type="button" onClick={close}>Cancel</button></div></form>}

function OfferCard({offer,busy,accept,cancel,reject}:{offer:any;busy:boolean;accept:()=>void;cancel:()=>void;reject:()=>void}){return <article className="panel trade-offer"><div className="offer-main"><span className={'trade-side '+offer.side}>{offer.side}</span><div><span className="eyebrow">{offer.channel==='private'?`DIRECT · ${offer.targetNation}`:`${offer.continent} ORIGIN`}</span><h3>{quantity(offer.quantity)} {labels[offer.resource]||offer.resource}</h3><p>{offer.nation} · {yen(offer.unitPrice)} per unit · {yen(offer.quantity*offer.unitPrice)} value</p></div></div><div className="logistics-preview"><span><Clock/>~{offer.estimatedTurns} turns</span><span>Shipping {yen(offer.estimatedFee)}</span><span>{Number(offer.distanceModifier).toFixed(2)}× distance</span><span>{Number(offer.riskPercent).toFixed(1)}% delay risk</span></div><div className="offer-action">{offer.isMine?<button disabled={busy} onClick={cancel}>Cancel and return escrow</button>:<><button className="primary" disabled={busy} onClick={accept}>{offer.side==='sell'?'Buy and dispatch':'Fulfill and dispatch'}<ArrowRight/></button>{offer.channel==='private'&&<button disabled={busy} onClick={reject}>Decline</button>}</>}</div></article>}

function ShipmentArea({shipments,selected,setSelected}:{shipments:any[];selected:any;setSelected:(x:any)=>void}){if(selected)return <ShipmentDetail shipment={selected} back={()=>{setSelected(undefined);go('/market/shipments')}}/>;return <div className="shipment-list">{shipments.length?shipments.map(shipment=><button className="panel shipment-row" key={shipment.id} onClick={()=>{setSelected(shipment);go('/market/shipment/'+encodeURIComponent(shipment.id))}}><span className={'shipment-status '+shipment.status}>{shipment.status.replace('_',' ')}</span><div><b>{quantity(shipment.quantity)} {labels[shipment.resource]||shipment.resource}</b><small>{shipment.seller} → {shipment.buyer}</small></div><div className="shipment-progress"><i style={{width:`${shipment.progress*100}%`}}/><span>{shipment.turnsRemaining} turns remaining</span></div><ArrowRight/></button>):<section className="panel trade-empty"><Ship/><h3>No shipments yet</h3><p>Accepted market and direct offers will be tracked here.</p></section>}</div>}

function ShipmentDetail({shipment,back}:{shipment:any;back:()=>void}){return <section className="shipment-detail"><button className="back" onClick={back}>← All shipments</button><div className="shipment-heading"><div><span className="eyebrow">SHIPMENT {String(shipment.id).slice(0,8).toUpperCase()}</span><h2>{quantity(shipment.quantity)} {labels[shipment.resource]||shipment.resource}</h2><p>{shipment.seller} → {shipment.buyer}</p></div><span className={'shipment-status '+shipment.status}>{shipment.status.replace('_',' ')}</span></div><TradeRouteMap shipment={shipment}/><div className="shipment-facts"><Fact label="Turns remaining" value={String(shipment.turnsRemaining)}/><Fact label="Estimated arrival" value={new Date(shipment.estimatedArrivalAt).toLocaleString()}/><Fact label="Goods value" value={yen(shipment.goodsValue)}/><Fact label="Shipping fee" value={yen(shipment.shippingFee)}/><Fact label="Distance" value={`${Number(shipment.distanceModifier).toFixed(2)}×`}/><Fact label="Delay risk" value={`${Number(shipment.riskPercent).toFixed(1)}%`}/></div></section>}
function Fact({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value}</b></div>}

function TradeRouteMap({shipment}:{shipment:any}){return <MaritimeTradeRouteMap shipment={shipment}/>}
