import {useEffect,useMemo,useState} from 'react';
import {Clock3,Hammer,LockKeyhole,ShieldCheck,Sparkles,Trash2} from 'lucide-react';
import './national-projects.css';

const request=async(path:string,options?:RequestInit)=>{const response=await fetch('/api'+path,{credentials:'include',headers:{'Content-Type':'application/json'},...options}),data=await response.json();if(!response.ok)throw Error(data.error||'Request failed.');return data};
const yen=(value:number)=>`¥${Number(value).toLocaleString()}`;
const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());

export default function NationalProjectsScreen(){
 const[data,setData]=useState<any>(),[category,setCategory]=useState('specialization'),[error,setError]=useState(''),[busy,setBusy]=useState('');
 const load=()=>request('/national-projects').then(setData).catch(e=>setError(e.message));useEffect(()=>{void load();const timer=setInterval(load,60000);return()=>clearInterval(timer)},[]);
 const groups=useMemo(()=>({specialization:data?.projects.filter((p:any)=>p.category==='specialization')||[],national:data?.projects.filter((p:any)=>p.category==='national')||[],military:data?.projects.filter((p:any)=>p.category==='military')||[]}),[data]);
 const act=async(project:any,demolish=false)=>{if(demolish&&!confirm(`Demolish ${project.name}? Its permanent bonus will be lost and nothing will be refunded.`))return;setBusy(project.id);setError('');try{await request('/national-projects'+(demolish?'/'+project.id:''),{method:demolish?'DELETE':'POST',body:demolish?undefined:JSON.stringify({project:project.id})});window.dispatchEvent(new Event('diplomatia:resources'));await load()}catch(e){setError((e as Error).message)}finally{setBusy('')}};
 if(!data)return <section className="panel wide">Opening the National Projects portfolio…</section>;
 const categories:any={specialization:['Economic Specializations','Permanent mega-boosts that make one commodity your national strength.'],national:['National Economy & Stats','Broad institutional projects layered onto the existing economy.'],military:['Military Industry Unlocks','Long-term industrial commitments that unlock future domestic production.']};
 return <div className="national-projects-page"><section className="projects-hero"><div><span className="eyebrow">PERMANENT NATIONAL DEVELOPMENT</span><h2>National Projects</h2><p>Expensive, slow strategic commitments that specialize your nation beyond its Gear, policies, Provinces, and existing economy.</p></div><Sparkles/></section><section className="project-slot-ledger"><div><span>Project slots</span><b>{data.used} / {data.slots}</b></div><div><span>Total Infrastructure</span><b>{Number(data.infrastructure).toLocaleString()}</b></div><div><span>Provinces</span><b>{data.provinces}</b></div><p>Nations begin with two long-term slots. Additional slots unlock slowly through Infrastructure and provincial expansion.</p></section>{error&&<p className="error notice">{error}</p>}<nav className="project-category-tabs">{Object.entries(categories).map(([key,value]:any)=><button className={category===key?'active':''} onClick={()=>setCategory(key)} key={key}>{key==='specialization'?<Hammer/>:key==='national'?<ShieldCheck/>:<LockKeyhole/>}{value[0]}</button>)}</nav><div className="project-category-intro"><span className="eyebrow">{categories[category][0].toUpperCase()}</span><h2>{categories[category][1]}</h2>{category==='specialization'&&<p>Only one completed or constructing mega-project may occupy each commodity exclusivity group. Other resources remain fully producible.</p>}</div><div className="long-project-grid">{groups[category as keyof typeof groups].map((project:any)=><article className={'panel long-project-card '+(project.completed?'complete ':project.construction?'building ':'')} key={project.id}><header><span className="project-category">{project.category}</span>{project.target&&<span className="project-target">{label(project.target)} exclusive</span>}</header><h3>{project.name}</h3><p>{project.description}</p><div className="project-cost"><b>{yen(project.cash)}</b>{Object.entries(project.costs).map(([resource,amount])=><span key={resource}>{Number(amount).toLocaleString()} {label(resource)}</span>)}</div>{project.construction?<div className="project-progress"><div><Clock3/><span>{project.construction.remaining} of {project.construction.total} turns remaining</span></div><i><b style={{width:`${(1-project.construction.remaining/project.construction.total)*100}%`}}/></i></div>:<small><Clock3/> {project.turns} hourly turns to construct</small>}<div className="project-actions">{project.completed?<><span className="operational"><ShieldCheck/>Operational</span><button className="danger" disabled={busy===project.id} onClick={()=>act(project,true)}><Trash2/>Demolish — no refund</button></>:project.construction?<span className="constructing"><Hammer/>Under construction</span>:<button className="primary" disabled={busy!==''||data.used>=data.slots} onClick={()=>act(project)}>{busy===project.id?'Locking resources…':'Begin construction'}</button>}</div></article>)}</div></div>;
}
