import {useEffect,useState} from 'react';
import {Bell,CheckCheck,Coins,ShieldAlert,ShoppingCart,Sparkles} from 'lucide-react';

const categories=[['all','All activity'],['economic','Economic'],['war','War'],['market','Market'],['game','Game']] as const;
const categoryMeta:Record<string,{label:string;icon:typeof Bell}>={economic:{label:'Economic',icon:Coins},war:{label:'War',icon:ShieldAlert},market:{label:'Market',icon:ShoppingCart},game:{label:'Game',icon:Sparkles}};
const request=async(path:string,body?:object)=>{const r=await fetch('/api'+path,{method:body?'PATCH':'GET',credentials:'include',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const text=await r.text();let data:any={};try{data=text?JSON.parse(text):{}}catch{throw Error(`Invalid server response (${r.status}).`)}if(!r.ok)throw Error(data.error||'Request failed');return data};
const relative=(raw:string)=>{const seconds=Math.max(0,Math.floor((Date.now()-new Date(raw).getTime())/1000));if(seconds<60)return'Less than a minute ago';const minutes=Math.floor(seconds/60);if(minutes<60)return`${minutes} ${minutes===1?'minute':'minutes'} ago`;const hours=Math.floor(minutes/60);if(hours<24)return`${hours} ${hours===1?'hour':'hours'} ago`;const days=Math.floor(hours/24);return`${days} ${days===1?'day':'days'} ago`};

function NotificationPager({page,total,setPage}:{page:number;total:number;setPage:(page:number)=>void}){const pages=Math.max(1,Math.ceil(total/10));if(pages<=1)return null;return <nav className="directory-pager" aria-label="Notification pages"><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} of {pages} · {total} notifications</span><button disabled={page===pages} onClick={()=>setPage(page+1)}>Next</button></nav>}

export default function NotificationsScreen(){
 const[category,setCategory]=useState('all'),[page,setPage]=useState(1),[data,setData]=useState<any>({items:[],unread:0}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=async(next=category)=>{try{setError('');setData(await request('/notifications'+(next==='all'?'':`?type=${next}`)))}catch(e){setError((e as Error).message)}};
 useEffect(()=>{setPage(1);void load(category)},[category]);
 const changed=()=>window.dispatchEvent(new Event('diplomatia:notifications'));
 const markOne=async(id:string,read:boolean)=>{if(read)return;try{await request('/notifications/read',{id});setData((d:any)=>({...d,unread:Math.max(0,d.unread-1),items:d.items.map((x:any)=>x.id===id?{...x,readAt:new Date().toISOString()}:x)}));changed()}catch(e){setError((e as Error).message)}};
 const markAll=async()=>{setBusy(true);try{await request('/notifications/read',{all:true,category:category==='all'?'':category});await load(category);changed()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const items=data.items||[],visible=items.slice((page-1)*10,page*10);
 return <div className="notifications-page"><section className="notification-hero"><div><Bell/><span className="eyebrow">NATIONAL ACTIVITY LOG</span><h2>Notifications</h2></div><div className="unread-summary"><b>{data.unread}</b><span>Unread</span></div></section>{error&&<p className="error notice">{error}</p>}<div className="notification-toolbar"><div className="notification-filters">{categories.map(([key,label])=><button className={category===key?'active':''} onClick={()=>setCategory(key)} key={key}>{label}</button>)}</div><button className="mark-read" disabled={busy||!items.some((x:any)=>!x.readAt)} onClick={markAll}><CheckCheck size={15}/>{busy?'Updating…':'Mark category as read'}</button></div><div className="notification-list">{items.length?visible.map((item:any)=>{const meta=categoryMeta[item.category]||categoryMeta.game,Icon=meta.icon;return <button className={'notification-item '+(item.readAt?'read':'unread')} onClick={()=>markOne(item.id,Boolean(item.readAt))} key={item.id}><div className={'notification-icon '+item.category}><Icon size={18}/></div><div><div className="notification-title"><span className="eyebrow">{meta.label}</span>{!item.readAt&&<i>NEW</i>}</div><h3>{item.title}</h3><p>{item.message}</p><time dateTime={item.createdAt} title={new Date(item.createdAt).toLocaleString()}>{relative(item.createdAt)}</time></div></button>}):<section className="panel notification-empty"><Bell/><h2>No notifications here</h2></section>}</div><NotificationPager page={page} total={items.length} setPage={setPage}/></div>
}
