import {useEffect,useState} from 'react';
import {BarChart3,Coins,Factory,Landmark} from 'lucide-react';
import './upkeep.css';
import RevenueLedger from './RevenueLedger';
import LuxuryConsumptionPanel from './LuxuryConsumptionPanel';

const yen=(n:number)=>`¥${Math.round(n||0).toLocaleString()}`;
const labels:Record<string,string>={foodstuffs:'Foodstuffs',timber:'Timber',fibers:'Fibers',basic_metals:'Basic Metals',energy:'Energy',strategic_minerals:'Strategic Minerals',textiles:'Textiles',processed_foods:'Processed Foods',construction_materials:'Construction Materials',basic_goods:'Basic Goods',consumer_goods:'Consumer Goods',military_equipment:'Military Equipment',luxury_goods:'Luxury Goods'};

export default function RevenueScreen(){
 const[data,setData]=useState<any>();
 const load=()=>Promise.all(['/economy','/strategy'].map(p=>fetch('/api'+p,{credentials:'include'}).then(r=>r.json()))).then(([economy,strategy])=>setData({economy,strategy}));
 useEffect(()=>{void load()},[]);
 if(!data)return <section className="panel wide">Preparing revenue accounts…</section>;
 const e=data.economy,r=e.result,s=data.strategy,m=s.result,a=Number(e.alliance.projectedDailyTax||0),military=Number(e.military?.dailyCashUpkeep||0),luxury=Number(e.luxuryConsumption?.projectedIncome||0),infrastructure=Number((r.dailyInfrastructureUpkeep??r.dailyUpkeep)||0),civic=Number(r.dailyCivicUpkeep||0),net=Number(r.dailyTax)+luxury-infrastructure-civic-military-a,gross=Math.max(1,r.dailyTax+luxury),rows=[['Gear-adjusted citizen tax',r.dailyTax,'positive'],['Luxury Consumption Income',luxury,'positive'],['Infrastructure upkeep',infrastructure,'negative'],['Civic Institution upkeep',civic,'negative'],['Military upkeep',military,'negative'],['Alliance tax',a,'negative'],['Net national revenue',net,'net']];
 return <div className="revenue-page">
  <section className="income-hero"><Coins/><div><span className="eyebrow">{s.gears.find((g:any)=>g.key===s.gear)?.name.toUpperCase()} · NEXT TURN {new Date(e.nextTurnAt).toLocaleTimeString()}</span><h2>{yen(net/24)} <small>net per hour</small></h2><p>{yen(net)} projected daily revenue after upkeep{e.alliance.name?` and ${e.alliance.name} tax`:''}</p></div></section>
  <div className="population-strip"><Metric label="Population" value={Math.round(r.population).toLocaleString()}/><Metric label="Effective employment" value={`${Number(r.effectiveEmploymentRate||0).toFixed(1)}%`}/><Metric label="Tax collection" value={`${Number(r.effectiveTaxCollectionMultiplier||1).toFixed(3)}×`}/><Metric label="Cash upkeep / hour" value={yen((Number(r.dailyUpkeep)+military)/24)}/><Metric label="Military Energy / day" value={`${Number(e.military?.dailyEnergyUpkeep||0).toFixed(2)} t`}/><Metric label="Food upkeep / hour" value={`${Number(r.hourlyFoodConsumption||0).toFixed(2)} t`}/><Metric label="Net food / day" value={`${Number(r.netDailyFood||0)>=0?'+':''}${Number(r.netDailyFood||0).toFixed(1)} t`}/><Metric label="Gear income effect" value={`${m.incomeMultiplier.toFixed(3)}×`}/><Metric label="Industry effect" value={`${m.industryMultiplier.toFixed(3)}×`}/><Metric label="Extraction effect" value={`${m.extractionMultiplier.toFixed(3)}×`}/></div>
  <LuxuryConsumptionPanel data={e.luxuryConsumption} onSaved={load}/>
  <section className="panel revenue-charts"><BarChart3/><span className="eyebrow">DAILY REVENUE COMPOSITION</span><h2>Where national income goes</h2>{rows.map(([label,raw,tone])=><RevenueBar key={String(label)} label={String(label)} value={Number(raw)} gross={gross} tone={String(tone)}/>)}<details className="city-revenue"><summary><span>Revenue by Province</span><small>{r.cities.length} Provinces</small></summary>{r.cities.map((c:any)=><div className="province-revenue-entry" key={c.id}><RevenueBar label={c.name} value={c.taxRevenue-c.upkeep} gross={gross} tone="city"/><small>{Number(c.employmentRate).toFixed(1)}% employed · {Number(c.taxCollectionMultiplier).toFixed(3)}× collection · {yen(c.civicUpkeep)} civic upkeep/day</small></div>)}</details></section>
  <section className="panel commodity-revenue"><Factory/><span className="eyebrow">REAL ECONOMY</span><h2>Projected commodity production</h2><p>Secondary output is realized only when the required input commodities are available at turn resolution.</p><div className="food-upkeep-summary"><div><span>Population food requirement</span><b>{Number(r.dailyFoodConsumption||0).toFixed(1)} t Foodstuffs / day</b></div><div><span>Foodstuffs production</span><b>+{Number(r.dailyFoodProduction||0).toFixed(1)} t / day</b></div><div><span>Net food balance</span><b className={Number(r.netDailyFood||0)<0?'negative':''}>{Number(r.netDailyFood||0)>=0?'+':''}{Number(r.netDailyFood||0).toFixed(1)} t / day</b></div></div><div className="commodity-grid">{Object.entries(m.production).map(([k,v])=><div key={k}><span>{labels[k]||k}</span><b>+{Number(v).toFixed(1)} t / day</b><small>{Number(s.stockpiles[k]||0).toLocaleString()} t on hand</small></div>)}</div></section>
  <RevenueLedger economy={e} strategy={s}/>
  <section className="panel revenue-factors"><Landmark/><h2>National income factors</h2>{Object.entries(r.contributors).map(([k,v])=><div className="factor" key={k}><span>{k}</span><b>{Number(v).toFixed(3)}</b></div>)}</section>
 </div>;
}

function RevenueBar({label,value,gross,tone}:{label:string,value:number,gross:number;tone:string}){return <div className={'revenue-row '+tone}><div><span>{label}</span><b>{yen(value)}</b></div><div className="revenue-track"><i style={{width:Math.min(100,Math.abs(value)/gross*100)+'%'}}/></div></div>}
function Metric({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value}</b></div>}
