import {useEffect,useState} from 'react';
import {BarChart3,Coins,Factory,Landmark} from 'lucide-react';
import './upkeep.css';
import RevenueLedger from './RevenueLedger';
import LuxuryConsumptionPanel from './LuxuryConsumptionPanel';
import EconomicDistressNotice from './EconomicDistressNotice';

const yen=(n:number)=>`¥${Math.round(n||0).toLocaleString()}`;
const labels:Record<string,string>={foodstuffs:'Foodstuffs',timber:'Timber',fibers:'Fibers',basic_metals:'Basic Metals',energy:'Energy',strategic_minerals:'Strategic Minerals',textiles:'Textiles',processed_foods:'Processed Foods',construction_materials:'Construction Materials',basic_goods:'Basic Goods',consumer_goods:'Consumer Goods',military_equipment:'Military Equipment',luxury_goods:'Luxury Goods'};

export default function RevenueScreen(){
 const[data,setData]=useState<any>();
 const load=()=>Promise.all(['/economy','/strategy'].map(p=>fetch('/api'+p,{credentials:'include'}).then(r=>r.json()))).then(([economy,strategy])=>setData({economy,strategy}));
 useEffect(()=>{void load()},[]);
 if(!data)return <section className="panel wide">Preparing revenue accounts…</section>;
 const e=data.economy,r=e.result,s=data.strategy,m=s.result,a=Number(e.alliance.projectedDailyTax||0),military=Number(e.military?.dailyCashUpkeep||0),luxury=Number(e.luxuryConsumption?.projectedIncome||0),infrastructure=Number((r.dailyInfrastructureUpkeep??r.dailyUpkeep)||0),civic=Number(r.dailyCivicUpkeep||0),net=Number(r.dailyTax)+luxury-infrastructure-civic-military-a,gross=Math.max(1,r.dailyTax+luxury),rows=[['Gear-adjusted citizen tax',r.dailyTax,'positive'],['Luxury Consumption Income',luxury,'positive'],['Infrastructure upkeep',infrastructure,'negative'],['Civic Institution upkeep',civic,'negative'],['Military upkeep',military,'negative'],['Alliance tax',a,'negative'],['Net national revenue',net,'net']];
 return <div className="revenue-page">
  <EconomicDistressNotice status={e.distress}/>
  <section className="income-hero"><Coins/><div><span className="eyebrow">{s.gears.find((g:any)=>g.key===s.gear)?.name.toUpperCase()} · NEXT TURN {new Date(e.nextTurnAt).toLocaleTimeString()}</span><h2>{yen(net/24)} <small>net per hour</small></h2><p>{yen(net)} projected daily revenue after upkeep{e.alliance.name?` and ${e.alliance.name} tax`:''}</p></div></section>
  <div className="population-strip"><Metric label="Population" value={Math.round(r.population).toLocaleString()}/><Metric label="Population growth / hour" value={`+${Number(r.projectedHourlyPopulationGrowth||0).toLocaleString()}`}/><Metric label="Population growth / day" value={`+${Number(r.projectedDailyPopulationGrowth||0).toLocaleString()}`}/><Metric label="Effective employment" value={`${Number(r.effectiveEmploymentRate||0).toFixed(1)}%`}/><Metric label="Tax collection" value={`${Number(r.effectiveTaxCollectionMultiplier||1).toFixed(3)}×`}/><Metric label="Cash upkeep / hour" value={yen((Number(r.dailyUpkeep)+military)/24)}/><Metric label="Military Energy / day" value={`${Number(e.military?.dailyEnergyUpkeep||0).toFixed(2)} t`}/><Metric label="Domestic food / hour" value={`${Number(r.hourlyFoodConsumption||0).toFixed(2)} t`}/><Metric label="War rations / day" value={`${Number(r.projectedDailyWarFoodConsumption||0).toFixed(2)} t`}/><Metric label="Net food / day" value={`${Number(r.netDailyFood||0)>=0?'+':''}${Number(r.netDailyFood||0).toFixed(1)} t`}/><Metric label="Gear income effect" value={`${m.incomeMultiplier.toFixed(3)}×`}/><Metric label="Industry effect" value={`${m.industryMultiplier.toFixed(3)}×`}/><Metric label="Extraction effect" value={`${m.extractionMultiplier.toFixed(3)}×`}/></div>
  <LuxuryConsumptionPanel data={e.luxuryConsumption} onSaved={load}/>
  <section className="panel revenue-charts"><BarChart3/><span className="eyebrow">DAILY REVENUE COMPOSITION</span><h2>Where national income goes</h2>{rows.map(([label,raw,tone])=><RevenueBar key={String(label)} label={String(label)} value={Number(raw)} gross={gross} tone={String(tone)}/>)}<details className="city-revenue"><summary><span>Revenue by Province</span><small>{r.cities.length} Provinces</small></summary>{r.cities.map((c:any)=><div className="province-revenue-entry" key={c.id}><RevenueBar label={c.name} value={c.taxRevenue-c.upkeep} gross={gross} tone="city"/><small>{Number(c.employmentRate).toFixed(1)}% employed · {Number(c.taxCollectionMultiplier).toFixed(3)}× collection · {yen(c.civicUpkeep)} civic upkeep/day</small></div>)}</details></section>
  <section className="panel commodity-revenue"><Factory/><span className="eyebrow">REAL ECONOMY</span><h2>Projected commodity production</h2><p>Secondary output is realized only when the required input commodities are available at turn resolution.</p><div className="food-upkeep-summary"><div><span>Domestic food requirement</span><b>{Number(r.dailyFoodConsumption||0).toFixed(1)} t Foodstuffs / day</b></div><div><span>Foodstuffs production</span><b>+{Number(r.dailyFoodProduction||0).toFixed(1)} t / day</b></div><div><span>Net food balance</span><b className={Number(r.netDailyFood||0)<0?'negative':''}>{Number(r.netDailyFood||0)>=0?'+':''}{Number(r.netDailyFood||0).toFixed(1)} t / day</b></div></div><div className="commodity-grid">{Object.entries(m.production).map(([k,v])=><div key={k}><span>{labels[k]||k}</span><b>+{Number(v).toFixed(1)} t / day</b><small>{Number(s.stockpiles[k]||0).toLocaleString()} t on hand</small></div>)}</div></section>
  <ProvinceProductionBreakdown strategy={s}/>
  <RevenueLedger economy={e} strategy={s}/>
  <section className="panel revenue-factors"><Landmark/><span className="eyebrow">TAX INCOME DRIVERS</span><h2>How to increase cash revenue</h2><p>Tax revenue grows through population, employment, Education, Satisfaction, Commerce, collection efficiency, and the Commercial & Trade upgrade. Civic services cost upkeep, so compare their added tax income against their daily cost.</p>{Object.entries(r.contributors).map(([k,v])=><IncomeFactor name={k} value={Number(v)} key={k}/>)}</section>
 </div>;
}

function RevenueBar({label,value,gross,tone}:{label:string,value:number,gross:number;tone:string}){return <div className={'revenue-row '+tone}><div><span>{label}</span><b>{yen(value)}</b></div><div className="revenue-track"><i style={{width:Math.min(100,Math.abs(value)/gross*100)+'%'}}/></div></div>}
function Metric({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value}</b></div>}
const incomeFactorLabels:Record<string,string>={localConditions:'Local conditions score',taxPenalty:'Tax-rate Satisfaction pressure',educationHappiness:'Education contribution to Satisfaction',effectiveEmploymentRate:'Effective employment',taxCollectionMultiplier:'Tax collection efficiency',currentHappiness:'Current Satisfaction',targetHappiness:'Long-term Satisfaction target',economicGearIncome:'Economic Gear income',economicDistressProductivity:'Food and upkeep productivity',dailyCrisisIncome:'Daily Crisis income',dailyCrisisUpkeepReduction:'Daily Crisis upkeep reduction'};
function IncomeFactor({name,value}:{name:string;value:number}){const percent=name.toLowerCase().includes('rate')||name.toLowerCase().includes('happiness')||name==='localConditions',multiplier=name.toLowerCase().includes('multiplier')||name==='economicGearIncome'||name==='dailyCrisisIncome';return <div className="factor"><span>{incomeFactorLabels[name]||name.replace(/([A-Z])/g,' $1')}</span><b>{multiplier?`${value.toFixed(3)}×`:percent?`${value.toFixed(1)}%`:value.toFixed(3)}</b></div>}
function ProvinceProductionBreakdown({strategy}:{strategy:any}){const provinces=strategy.provinces||[],production=strategy.result?.provinceProduction||{},factors=strategy.result?.provinceFactors||{};return <section className="panel province-production-breakdown"><Factory/><span className="eyebrow">PRODUCTION BY PROVINCE</span><h2>What determines resource output</h2><p>Employment raises operating efficiency. Disease and crime reduce it. Production upgrades increase output but also create the pressure that Hospitals, Police Stations, Recovery Works, Education, and employment must control.</p>{provinces.map((province:any)=>{const output=production[province.ID]||{},factor=factors[province.ID]||{},items=Object.entries(output).filter(([,amount])=>Number(amount)>0);return <details key={province.ID}><summary><span><b>{province.Name}</b><small>{province.Specialization} specialization · {Math.round(province.Infra)} Infrastructure</small></span><strong>{Number(factor.operationalFactor||1).toFixed(3)}× efficiency</strong></summary><div className="province-production-factors"><span>Employment <b>{Number(factor.employmentRate||0).toFixed(1)}%</b></span><span>Disease <b>{(Number(factor.diseaseRate||0)*100).toFixed(1)}%</b></span><span>Crime <b>{(Number(factor.crimeRate||0)*100).toFixed(1)}%</b></span><span>Workforce <b>{Number(factor.workforceFactor||1).toFixed(3)}×</b></span><span>Health <b>{Number(factor.healthFactor||1).toFixed(3)}×</b></span><span>Security <b>{Number(factor.securityFactor||1).toFixed(3)}×</b></span></div><div className="province-production-resources">{items.map(([key,amount])=><span key={key}><b>{labels[key]||key}</b><strong>+{Number(amount).toFixed(2)} t/day</strong></span>)}</div><p className="production-advice">Increase primary resources with Infrastructure, deposit upgrades, and matching specialization. Increase commodities with quotas and Light/Heavy/Military Industry. If efficiency falls, invest in employment, health, pollution control, or security before expanding production further.</p></details>})}</section>}
