import {useEffect,useState} from 'react';
import {Factory,MapPin,Plus,SlidersHorizontal,Tractor} from 'lucide-react';
const api=async(path:string,body?:object,method?:string)=>{const r=await fetch('/api'+path,{method:method||(body?'PATCH':'GET'),credentials:'include',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const text=await r.text();let x:any={};try{x=text?JSON.parse(text):{}}catch{x={error:text||'Request failed'}}if(!r.ok)throw Error(x.error||'Request failed');return x};
const labels:Record<string,string>={foodstuffs:'Foodstuffs',timber:'Timber',fibers:'Fibers',basic_metals:'Basic Metals',energy:'Energy',strategic_minerals:'Strategic Minerals',textiles:'Textiles',processed_foods:'Processed Foods',construction_materials:'Construction Materials',basic_goods:'Basic Goods',consumer_goods:'Consumer Goods',military_equipment:'Military Equipment',luxury_goods:'Luxury Goods'};
const goods=['textiles','processed_foods','construction_materials','basic_goods','consumer_goods','military_equipment','luxury_goods'];
const effectNames:Record<string,string>={population:'Population growth',extraction:'Resource extraction',industry:'Commodity output',commerce:'Cash income',military:'Military production',happiness:'Happiness',education:'Education'};
const specializations:Record<string,{name:string;description:string}>={mixed:{name:'Mixed',description:'Flexible, with no focused bonus.'},agriculture:{name:'Agriculture',description:'+22% local food and fiber deposits.'},extraction:{name:'Extraction',description:'+18% output from all local deposits.'},industry:{name:'Industry',description:'+20% local commodity capacity.'},commerce:{name:'Commerce',description:'+1.5% national cash income.'},military:{name:'Military',description:'+2.5% national military production.'}};
function Effects({values}:{values:Record<string,number>}){const items=Object.entries(values).filter(([,v])=>Math.abs(v-1)>.0001);return <div className="effect-list">{items.length?items.map(([k,v])=><span className={v>=1?'positive':'negative'} key={k}><b>{v>=1?'+':''}{((v-1)*100).toFixed(0)}%</b> {effectNames[k]||k}</span>):<span className="neutral">No direct bonuses or penalties</span>}</div>}
export default function StrategicEconomyScreen(){
 const[data,setData]=useState<any>(),[error,setError]=useState(''),[quotas,setQuotas]=useState<Record<string,number>>({}),[selectedGear,setSelectedGear]=useState(''),[policyDraft,setPolicyDraft]=useState<string[]>([]),[provinceName,setProvinceName]=useState('');
 const load=()=>api('/strategy').then(x=>{setData(x);setSelectedGear(x.gear);setPolicyDraft(x.policies.filter((p:any)=>p.active).map((p:any)=>p.key));setQuotas(Object.fromEntries(goods.map(k=>[k,Number(x.quotas[k]||0)])))}).catch(e=>setError(e.message));
 useEffect(()=>{void load()},[]);const act=async(path:string,body:object,method='PATCH')=>{try{setError('');await api(path,body,method);await load()}catch(e){setError((e as Error).message)}};
 if(!data)return <section className="panel wide">Mapping the national economy…</section>;const total=Object.values(quotas).reduce((a,b)=>a+b,0),active:string[]=data.policies.filter((x:any)=>x.active).map((x:any)=>x.key),policyChanged=[...active].sort().join('|')!==[...policyDraft].sort().join('|'),newPolicies=policyDraft.filter(k=>!active.includes(k)),policyCost=newPolicies.reduce((sum,k)=>sum+Number(data.policies.find((p:any)=>p.key===k)?.cost||0),0);
 const setQuota=(key:string,value:number)=>setQuotas({...quotas,[key]:Math.max(0,Math.min(100,Number.isFinite(value)?value:0))});const distributeEvenly=()=>{const share=Math.floor(10000/goods.length)/100;setQuotas(Object.fromEntries(goods.map((k,i)=>[k,i===goods.length-1?100-share*(goods.length-1):share])))};const togglePolicy=(key:string)=>{setError('');if(policyDraft.includes(key)){setPolicyDraft(policyDraft.filter(k=>k!==key));return}if(policyDraft.length>=2){setError('Choose no more than two social policies.');return}setPolicyDraft([...policyDraft,key])};
 const found=async()=>{if(!provinceName.trim()){setError('Enter a name for the new Province.');return}await act('/cities',{name:provinceName.trim()},'POST');setProvinceName('')};
 return <div className="strategy-page">{error&&<p className="error notice">{error}</p>}
 <section className="strategy-hero"><div><span className="eyebrow">NATIONAL ECONOMIC IDENTITY</span><h2>{data.gears.find((g:any)=>g.key===data.gear)?.name}</h2><p>Gearing rewards a coherent national strategy while leaving room for specialized Provinces.</p></div><div><b>{data.politicalCapital.toFixed(1)}</b><span>Political capital</span></div></section>
 <section><Heading icon={<SlidersHorizontal/>} kicker="ECONOMIC GEAR" title="Choose the direction of national growth" text="Gear multipliers affect the entire nation. Preview a Gear, then explicitly save it."/><div className="gear-grid">{data.gears.map((g:any)=><button className={'panel gear-card '+(g.key===selectedGear?'selected':'')} key={g.key} onClick={()=>setSelectedGear(g.key)}><b>{g.name}</b><p>{g.description}</p><Effects values={g.effects}/>{g.key===data.gear&&<small>CURRENT GEAR</small>}</button>)}</div><p className="choice-cost"><b>Changing Gear costs:</b> 25 political capital and 5 Happiness. Output falls to 75% for 24 hours, with a seven-day lock.</p>{selectedGear!==data.gear&&<div className="gear-confirm"><div><b>Confirm {data.gears.find((g:any)=>g.key===selectedGear)?.name}?</b><span>This choice carries the costs and lock described above.</span></div><button className="primary" onClick={()=>act('/strategy/gear',{gear:selectedGear})}>Save and lock this Gear</button><button onClick={()=>setSelectedGear(data.gear)}>Cancel</button></div>}</section>
 <section><Heading kicker="SOCIAL POLICIES" title="Fine-tune the national model" text="Select up to two policies. Nothing changes until saved."/><div className="policy-selection-status"><span><b>{policyDraft.length} / 2</b> policies selected</span><small>New policies cost political capital; retaining or removing one is free.</small></div><div className="policy-grid">{data.policies.map((p:any)=>{const selected=policyDraft.includes(p.key),wasActive=active.includes(p.key);return <button className={'panel policy-card '+(selected?'selected ':'')+(wasActive&&!selected?'pending-removal':'')} key={p.key} onClick={()=>togglePolicy(p.key)}><b>{p.name}</b><p>{p.description}</p><Effects values={p.effects}/><small>{wasActive&&selected?'CURRENT · Retained':wasActive?'PENDING REMOVAL · Free':selected?`PENDING ADOPTION · ${p.cost} political capital`:`AVAILABLE · ${p.cost} political capital`}</small></button>})}</div>{policyChanged&&<div className="policy-save"><div><b>Unsaved policy changes</b><span>{newPolicies.length?`Adoption cost: ${policyCost} political capital.`:'No political capital will be spent.'}</span></div><button className="primary" disabled={policyCost>data.politicalCapital} onClick={()=>act('/strategy/policies',{policies:policyDraft})}>Save social policies</button><button onClick={()=>setPolicyDraft(active)}>Cancel</button></div>}</section>
 <section className="panel quota-panel"><div className="quota-heading"><div><Factory/><span className="eyebrow">NATIONAL PRODUCTION PRIORITIES</span><h2>Commodity quotas</h2><p>Divide industrial capacity between commodities. Recipes show inputs consumed per unit.</p></div><div className={'allocation-gauge '+(total>100?'invalid':'')}><span>CAPACITY ALLOCATED</span><b>{total.toFixed(1)}%</b><div><i style={{width:Math.min(total,100)+'%'}}/></div><small>{total>100?`Reduce by ${(total-100).toFixed(1)}%`:`${(100-total).toFixed(1)}% remains idle`}</small></div></div><div className="quota-tools"><button onClick={distributeEvenly}>Allocate evenly</button><button onClick={()=>setQuotas(Object.fromEntries(goods.map(k=>[k,0])))}>Clear all</button></div><div className="quota-grid">{goods.map(k=><article className={'quota-card '+(quotas[k]>0?'active':'')} key={k}><div className="quota-card-head"><div><b>{labels[k]}</b><span>{quotas[k].toFixed(1)}% of capacity</span></div><label><input type="number" step="0.1" min="0" max="100" value={Number(quotas[k].toFixed(2))} onChange={e=>setQuota(k,Number(e.target.value))}/><b>%</b></label></div><input className="quota-slider" type="range" step="0.5" min="0" max="100" value={quotas[k]} onChange={e=>setQuota(k,Number(e.target.value))}/><div className="recipe"><span>INPUTS PER UNIT</span><div>{Object.entries(data.recipes[k]||{}).map(([input,amount])=><small key={input}><b>{Number(amount).toFixed(2)}</b> {labels[input]} <em>{Number(data.stockpiles[input]||0).toLocaleString()} on hand</em></small>)}</div></div></article>)}</div><div className="quota-actions"><div><b>{total<=100?'Ready to save':'Allocation exceeds 100%'}</b><span>{total<100?'Unused capacity remains idle.':total===100?'All capacity is assigned.':'Lower quotas before saving.'}</span></div><button className="primary" disabled={total>100} onClick={()=>act('/strategy/quotas',{quotas})}>Save production priorities</button></div></section>
 <section><Heading icon={<MapPin/>} kicker="PROVINCIAL DEVELOPMENT" title="Develop locally, then expand" text="Infrastructure expands population and upgrade capacity. Upgrade returns soften after level 8, making a new Province increasingly attractive."/>
 <div className="panel expansion-card"><div><span className="eyebrow">FOUND PROVINCE {data.expansion.provinceCount+1}</span><h3>Geographic expansion</h3><p>{data.expansion.formula}. Every Province raises the next cash and construction requirement.</p></div><div className="expansion-costs"><span><b>¥{Number(data.expansion.cashCost).toLocaleString()}</b> Treasury</span><span><b>{Number(data.expansion.constructionMaterials).toLocaleString()}</b> Construction Materials</span><span><b>−{data.expansion.happinessStrain}</b> temporary Happiness strain</span></div><small>Current modifiers: Gear ×{Number(data.expansion.gearModifier).toFixed(2)}, policies ×{Number(data.expansion.policyModifier).toFixed(2)}.</small>{data.expansion.nextProvinceAt?<p className="cooldown">Expansion available {new Date(data.expansion.nextProvinceAt).toLocaleString()}</p>:<div className="found-province"><input value={provinceName} maxLength={80} placeholder="New Province name" onChange={e=>setProvinceName(e.target.value)}/><button className="primary" onClick={found}><Plus size={15}/> Found Province</button></div>}</div>
 <div className="province-grid">{data.provinces.map((p:any)=><article className="panel province-card" key={p.ID}><div className="province-head"><div><span className="eyebrow">PROVINCE · {Math.round(p.Infra)} INFRASTRUCTURE</span><h3>{p.Name}</h3></div><span className="cap-chip">Upgrade cap {p.UpgradeCap}/15</span></div><div className="deposit-list">{Object.entries(p.Deposits).map(([k,v])=><span key={k}><b>{labels[k]}</b>{Number(v).toFixed(2)}× richness</span>)}</div><label>Specialization<select value={p.Specialization} onChange={e=>act('/strategy/province',{provinceID:p.ID,specialization:e.target.value,developmentInvestment:0})}>{Object.entries(specializations).map(([key,s])=><option key={key} value={key}>{s.name}</option>)}</select><small className="choice-explanation">{specializations[p.Specialization]?.description}</small></label><div className="infra-invest"><div><b>Infrastructure</b><small>Raises population and unlocks upgrade levels. Its unit cost rises continuously.</small></div>{[10,50,100].map(amount=><button key={amount} onClick={()=>act('/economy/development',{cityID:p.ID,kind:'infrastructure',amount},'POST')}>+{amount}<small>¥{Number(p.InfrastructureQuotes[String(amount)]).toLocaleString()}</small></button>)}</div><div className="upgrade-list">{data.provinceUpgradeTypes.map((u:any)=>{const level=Number(p.Upgrades[u.key]||0),capped=level>=p.UpgradeCap||level>=15;return <div className="province-upgrade" key={u.key}><div><b>{u.name}</b><span>Level {level} / {p.UpgradeCap}</span><p>{u.description}</p>{level>=8&&level<15&&<small className="diminishing">Diminishing returns active</small>}</div><button disabled={capped} onClick={()=>act('/strategy/province/upgrade',{provinceID:p.ID,upgrade:u.key},'POST')}>{level>=15?'Hard cap':level>=p.UpgradeCap?'Needs Infrastructure':<>Raise to {level+1}<small>¥{Number(p.UpgradeQuotes[u.key]).toLocaleString()}</small></>}</button></div>})}</div></article>)}</div></section>
 <section className="panel commodity-output"><Tractor/><h2>Projected daily commodity output</h2><div className="commodity-grid">{Object.entries(data.result.production).map(([k,v])=><div key={k}><span>{labels[k]||k}</span><b>+{Number(v).toFixed(1)}</b><small>{Number(data.stockpiles[k]||0).toLocaleString()} stockpiled</small></div>)}</div></section></div>;
}
function Heading({icon,kicker,title,text}:{icon?:React.ReactNode,kicker:string,title:string,text?:string}){return <div className="section-intro">{icon}<span className="eyebrow">{kicker}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
