import {useEffect,useState} from 'react';
import {Factory,MapPin,RefreshCw,SlidersHorizontal,Tractor} from 'lucide-react';
const api=async(path:string,body?:object)=>{const r=await fetch('/api'+path,{method:body?'PATCH':'GET',credentials:'include',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const x=await r.json();if(!r.ok)throw Error(x.error||'Request failed');return x};
const labels:Record<string,string>={foodstuffs:'Foodstuffs',timber:'Timber',fibers:'Fibers',basic_metals:'Basic Metals',energy:'Energy',strategic_minerals:'Strategic Minerals',textiles:'Textiles',processed_foods:'Processed Foods',construction_materials:'Construction Materials',basic_goods:'Basic Goods',consumer_goods:'Consumer Goods',military_equipment:'Military Equipment',luxury_goods:'Luxury Goods'};
const goods=['textiles','processed_foods','construction_materials','basic_goods','consumer_goods','military_equipment','luxury_goods'];
const effectNames:Record<string,string>={population:'Population growth',extraction:'Resource extraction',industry:'Commodity output',commerce:'Cash income',military:'Military production',happiness:'Happiness',education:'Education'};
const specializations:Record<string,{name:string;description:string}>={mixed:{name:'Mixed',description:'No specialization bonus; a flexible neutral choice.'},agriculture:{name:'Agriculture',description:'+22% output from every local natural deposit.'},extraction:{name:'Extraction',description:'+18% output from every local natural deposit.'},industry:{name:'Industry',description:'+20% local secondary commodity capacity.'},commerce:{name:'Commerce',description:'+1.5% national cash-income multiplier for this Province.'},military:{name:'Military',description:'+2.5% national military-equipment multiplier for this Province.'}};
function Effects({values}:{values:Record<string,number>}){const items=Object.entries(values).filter(([,v])=>Math.abs(v-1)>.0001);return <div className="effect-list">{items.length?items.map(([k,v])=><span className={v>=1?'positive':'negative'} key={k}><b>{v>=1?'+':''}{((v-1)*100).toFixed(0)}%</b> {effectNames[k]||k}</span>):<span className="neutral">No direct bonuses or penalties</span>}</div>}
export default function StrategicEconomyScreen(){
 const[data,setData]=useState<any>(),[error,setError]=useState(''),[quotas,setQuotas]=useState<Record<string,number>>({}),[selectedGear,setSelectedGear]=useState('');
 const load=()=>api('/strategy').then(x=>{setData(x);setSelectedGear(x.gear);setQuotas(Object.fromEntries(goods.map(k=>[k,Number(x.quotas[k]||0)])))}).catch(e=>setError(e.message));
 useEffect(()=>{void load()},[]);const act=async(path:string,body:object)=>{try{setError('');await api(path,body);await load()}catch(e){setError((e as Error).message)}};
 if(!data)return <section className="panel wide">Mapping the national economy…</section>;const total=Object.values(quotas).reduce((a,b)=>a+b,0),active=data.policies.filter((x:any)=>x.active).map((x:any)=>x.key);
 const setQuota=(key:string,value:number)=>setQuotas({...quotas,[key]:Math.max(0,Math.min(100,Number.isFinite(value)?value:0))});
 const distributeEvenly=()=>{const share=Math.floor(10000/goods.length)/100;setQuotas(Object.fromEntries(goods.map((k,i)=>[k,i===goods.length-1?100-share*(goods.length-1):share])))};
 return <div className="strategy-page">{error&&<p className="error notice">{error}</p>}
 <section className="strategy-hero"><div><span className="eyebrow">NATIONAL ECONOMIC IDENTITY</span><h2>{data.gears.find((g:any)=>g.key===data.gear)?.name}</h2><p>Gearing rewards a coherent national strategy while leaving room for specialized Provinces.</p></div><div><b>{data.politicalCapital.toFixed(1)}</b><span>Political capital</span></div></section>
 <section><Heading icon={<SlidersHorizontal/>} kicker="ECONOMIC GEAR" title="Choose the direction of national growth" text="Gear multipliers affect the entire nation and combine with policies and Province bonuses. Select a Gear to preview it; nothing changes until you confirm."/><div className="gear-grid">{data.gears.map((g:any)=><button className={'panel gear-card '+(g.key===selectedGear?'selected':'')} key={g.key} onClick={()=>setSelectedGear(g.key)}><b>{g.name}</b><p>{g.description}</p><Effects values={g.effects}/>{g.key===data.gear&&<small>CURRENT GEAR</small>}</button>)}</div><p className="choice-cost"><b>Changing Gear costs:</b> 25 political capital and 5 Happiness. Output falls to 75% for 24 hours, and you may change again after seven days.</p>{selectedGear!==data.gear&&<div className="gear-confirm"><div><b>Confirm {data.gears.find((g:any)=>g.key===selectedGear)?.name}?</b><span>This spends 25 political capital, reduces Happiness by 5, disrupts output for 24 hours, and locks Gear changes for seven days.</span></div><button className="primary" onClick={()=>act('/strategy/gear',{gear:selectedGear})}>Save and lock this Gear</button><button onClick={()=>setSelectedGear(data.gear)}>Cancel</button></div>}</section>
 <section><Heading kicker="SOCIAL POLICIES" title="Fine-tune the national model" text="Choose up to two. You pay only when adopting a policy; keeping an active policy or deactivating it is free."/><div className="policy-grid">{data.policies.map((p:any)=><button className={'panel policy-card '+(p.active?'selected':'')} key={p.key} onClick={()=>act('/strategy/policies',{policies:p.active?active.filter((k:string)=>k!==p.key):[...active,p.key]})}><b>{p.name}</b><p>{p.description}</p><Effects values={p.effects}/><small>{p.active?'ACTIVE · Click to deactivate free':`ADOPT · ${p.cost} political capital`}</small></button>)}</div></section>
 <section className="panel quota-panel"><div className="quota-heading"><div><Factory/><span className="eyebrow">NATIONAL PRODUCTION PRIORITIES</span><h2>Commodity quotas</h2><p>Divide industrial capacity between commodities. Recipes show the stockpiled inputs consumed for every unit produced.</p></div><div className={'allocation-gauge '+(total>100?'invalid':'')}><span>{total>100?'OVER CAPACITY':'CAPACITY ALLOCATED'}</span><b>{total.toFixed(1)}%</b><div><i style={{width:Math.min(total,100)+'%'}}/></div><small>{total>100?`Reduce quotas by ${(total-100).toFixed(1)}%`:`${(100-total).toFixed(1)}% remains idle`}</small></div></div><div className="quota-tools"><button type="button" onClick={distributeEvenly}>Allocate evenly</button><button type="button" onClick={()=>setQuotas(Object.fromEntries(goods.map(k=>[k,0])))}>Clear all</button></div><div className="quota-grid">{goods.map(k=>{const recipe=Object.entries(data.recipes[k]||{});return <article className={'quota-card '+(quotas[k]>0?'active':'')} key={k}><div className="quota-card-head"><div><b>{labels[k]}</b><span>{quotas[k]>0?`${quotas[k].toFixed(1)}% of capacity`:'Not produced'}</span></div><label><input aria-label={`${labels[k]} quota`} type="number" step="0.1" min="0" max="100" value={Number(quotas[k].toFixed(2))} onChange={e=>setQuota(k,Number(e.target.value))}/><b>%</b></label></div><input className="quota-slider" aria-label={`${labels[k]} quota slider`} type="range" step="0.5" min="0" max="100" value={quotas[k]} onChange={e=>setQuota(k,Number(e.target.value))}/><div className="recipe"><span>INPUTS PER UNIT</span><div>{recipe.map(([input,amount])=><small key={input}><b>{Number(amount).toFixed(2)}</b> {labels[input]} <em>{Number(data.stockpiles[input]||0).toLocaleString()} on hand</em></small>)}</div></div></article>})}</div><div className="quota-actions"><div><b>{total<=100?'Ready to save':'Allocation exceeds 100%'}</b><span>{total<100?'Unused capacity will remain idle.':total===100?'All industrial capacity is assigned.':'Lower one or more quotas before saving.'}</span></div><button className="primary" disabled={total>100} onClick={()=>act('/strategy/quotas',{quotas})}>Save production priorities</button></div></section>
 <section><Heading icon={<MapPin/>} kicker="PROVINCES & REGIONS" title="Local specialization and development" text="Specializations are free to change. Development permanently improves a Province, with a cost that rises quadratically."/><div className="province-grid">{data.provinces.map((p:any)=>{const developmentCost=25000*p.Development*p.Development;return <article className="panel province-card" key={p.ID}><span className="eyebrow">DEVELOPMENT {p.Development}</span><h3>{p.Name}</h3><p>{Math.round(p.Infra)} Infrastructure</p><div className="deposit-list">{Object.entries(p.Deposits).map(([k,v])=><span key={k}><b>{labels[k]}</b>{Number(v).toFixed(2)}× deposit richness</span>)}</div><label>Specialization<select value={p.Specialization} onChange={e=>act('/strategy/province',{provinceID:p.ID,specialization:e.target.value,developmentInvestment:0})}>{Object.entries(specializations).map(([key,s])=><option key={key} value={key}>{s.name}</option>)}</select><small className="choice-explanation">{specializations[p.Specialization]?.description}</small></label><p className="development-explanation">Each Development level adds <b>+2.5%</b> local deposit output and commodity capacity.</p><button className="primary" onClick={()=>act('/strategy/province',{provinceID:p.ID,specialization:p.Specialization,developmentInvestment:1})}><RefreshCw size={14}/> Raise to {p.Development+1} · ¥{developmentCost.toLocaleString()}</button></article>})}</div></section>
 <section className="panel commodity-output"><Tractor/><h2>Projected daily commodity output</h2><div className="commodity-grid">{Object.entries(data.result.production).map(([k,v])=><div key={k}><span>{labels[k]||k}</span><b>+{Number(v).toFixed(1)}</b><small>{Number(data.stockpiles[k]||0).toLocaleString()} stockpiled</small></div>)}</div></section></div>
}
function Heading({icon,kicker,title,text}:{icon?:React.ReactNode,kicker:string,title:string,text?:string}){return <div className="section-intro">{icon}<span className="eyebrow">{kicker}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
