import {useEffect,useState} from 'react';
import {Building2,Check,ChevronDown,Factory,Info,Landmark,MapPin,Pencil,Plus,SlidersHorizontal,Tractor,X} from 'lucide-react';
import './province-action-errors.css';
import './province-upgrade-benefits.css';
import ResourceIcon from './ResourceIcon';
import EconomicDistressNotice from './EconomicDistressNotice';

const api=async(path:string,body?:object,method?:string)=>{const response=await fetch('/api'+path,{method:method||(body?'PATCH':'GET'),credentials:'include',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const text=await response.text();let result:any={};try{result=text?JSON.parse(text):{}}catch{result={error:text||'Request failed'}}if(!response.ok)throw Error(result.error||'Request failed');return result};
const labels:Record<string,string>={foodstuffs:'Foodstuffs',timber:'Timber',fibers:'Fibers',basic_metals:'Basic Metals',energy:'Energy',strategic_minerals:'Strategic Minerals',textiles:'Textiles',processed_foods:'Processed Foods',construction_materials:'Construction Materials',basic_goods:'Basic Goods',consumer_goods:'Consumer Goods',military_equipment:'Military Equipment',luxury_goods:'Luxury Goods'};
const goods=['textiles','processed_foods','construction_materials','basic_goods','consumer_goods','military_equipment','luxury_goods'];
const effectNames:Record<string,string>={population:'Population growth',extraction:'Resource extraction',industry:'Commodity output',commerce:'Cash income',military:'Military production',happiness:'Happiness',education:'Education gain',disease:'Disease',crime:'Crime',employment:'Employment rate',foodConsumption:'Food consumption',infrastructureUpkeep:'Infrastructure upkeep'};
const specializations:Record<string,{name:string;description:string}>={mixed:{name:'Mixed',description:'Flexible, with no focused bonus.'},agriculture:{name:'Agriculture',description:'+22% local food and fiber deposits.'},extraction:{name:'Extraction',description:'+18% output from all local deposits.'},industry:{name:'Industry',description:'+20% local commodity capacity.'},commerce:{name:'Commerce',description:'+1.5% national cash income.'},military:{name:'Military',description:'+2.5% national military production.'}};
const money=(value:number)=>`¥${Number(value||0).toLocaleString()}`;

function Effects({values}:{values:Record<string,number>}){const reductions=new Set(['disease','crime','foodConsumption','infrastructureUpkeep']),items=Object.entries(values).filter(([,value])=>Math.abs(value-1)>.0001);return <div className="effect-list">{items.length?items.map(([key,value])=>{const beneficial=value>=1!==reductions.has(key);return <span className={beneficial?'positive':'negative'} key={key}><b>{value>=1?'+':''}{((value-1)*100).toFixed(0)}%</b> {effectNames[key]||key}</span>}):<span className="neutral">No direct modifiers</span>}</div>}
function GearGlyph({gear}:{gear:string}){const Icon=gear==='agrarian'?Tractor:gear==='commercial'?Landmark:gear==='industrial'?Factory:gear==='militarized'?Building2:SlidersHorizontal;return <Icon aria-hidden="true"/>}
function InfoTip({label,children}:{label:string;children:React.ReactNode}){return <span className="economy-help" tabIndex={0} aria-label={label}><Info/><span role="tooltip"><b>{label}</b>{children}</span></span>}

export default function StrategicEconomyScreen(){
 const[data,setData]=useState<any>(),[error,setError]=useState(''),[activeTab,setActiveTab]=useState<'economy'|'provinces'>('economy'),[selectedProvinceID,setSelectedProvinceID]=useState(''),[quotas,setQuotas]=useState<Record<string,number>>({}),[savedQuotas,setSavedQuotas]=useState<Record<string,number>>({}),[selectedGear,setSelectedGear]=useState(''),[policyDraft,setPolicyDraft]=useState<string[]>([]),[provinceName,setProvinceName]=useState(''),[renaming,setRenaming]=useState(''),[renameDraft,setRenameDraft]=useState('');
 const load=()=>api('/strategy').then(result=>{const allocations=Object.fromEntries(goods.map(key=>[key,Number(result.quotas[key]||0)]));setData(result);setSelectedGear(result.gear);setPolicyDraft(result.policies.filter((policy:any)=>policy.active).map((policy:any)=>policy.key));setQuotas(allocations);setSavedQuotas(allocations)}).catch(reason=>setError(reason.message));
 useEffect(()=>{void load()},[]);
 const confirmationFor=(path:string,body:any,method:string)=>{
  if(method==='POST'&&path==='/cities')return `Found ${body.name}? This spends ${money(data?.expansion?.cashCost||0)}, ${Number(data?.expansion?.constructionMaterials||0).toLocaleString()} Construction Materials, and applies temporary Happiness strain.`;
  if(path==='/economy/development'&&body.kind==='infrastructure')return '';
  if(method==='POST'&&path==='/economy/improvements'){const institution=data?.civicInstitutions?.find((item:any)=>item.key===body.building);if(institution){const resources=Object.entries(institution.resourceCosts||{}).map(([key,value])=>`${Number(value).toLocaleString()} t ${labels[key]||key}`).join(', ');return `Build ${institution.name}? This spends ${money(institution.cashCost)}${resources?` and ${resources}`:''}, and adds ${money(institution.dailyUpkeep)} to daily civic upkeep.`}}
  if(method==='POST'&&path==='/strategy/province/upgrade'){const province=data?.provinces?.find((item:any)=>item.ID===body.provinceID),upgrade=data?.provinceUpgradeTypes?.find((item:any)=>item.key===body.upgrade);if(body.action==='downgrade')return `Lower ${upgrade?.name||'this upgrade'} in ${province?.Name||'this Province'}? Downgrades return no resources or Treasury.`;return `Raise ${upgrade?.name||'this upgrade'} in ${province?.Name||'this Province'}? This spends ${money(province?.UpgradeQuotes?.[body.upgrade]||0)}.`}
  return '';
 };
 const act=async(path:string,body:object,method='PATCH')=>{const confirmation=confirmationFor(path,body,method);if(confirmation&&!window.confirm(confirmation))return false;try{setError('');await api(path,body,method);await load();return true}catch(reason){setError((reason as Error).message);return false}};
 if(!data)return <section className="panel wide">Mapping the national economy…</section>;

 const total=Object.values(quotas).reduce((sum,value)=>sum+value,0),quotaChanged=goods.some(key=>Math.abs(Number(quotas[key]||0)-Number(savedQuotas[key]||0))>.001),active:string[]=data.policies.filter((policy:any)=>policy.active).map((policy:any)=>policy.key),policyChanged=[...active].sort().join('|')!==[...policyDraft].sort().join('|'),newPolicies=policyDraft.filter(key=>!active.includes(key)),policyCost=newPolicies.reduce((sum,key)=>sum+Number(data.policies.find((policy:any)=>policy.key===key)?.cost||0),0),province=data.provinces.find((item:any)=>item.ID===selectedProvinceID)||data.provinces[0],currentGear=data.gears.find((gear:any)=>gear.key===data.gear),previewGear=data.gears.find((gear:any)=>gear.key===selectedGear);
 const setQuota=(key:string,value:number)=>{const next=Math.max(0,Math.min(100,Number.isFinite(value)?value:0)),current=Number(quotas[key]||0),increase=next-current,available=Math.max(0,100-total),overflow=Math.max(0,increase-available),othersTotal=Math.max(0,total-current),updated={...quotas,[key]:next};if(overflow>0&&othersTotal>0)for(const item of goods)if(item!==key)updated[item]=Math.max(0,Number(quotas[item]||0)-overflow*(Number(quotas[item]||0)/othersTotal));setQuotas(updated)};
 const applyQuotaPreset=(preset:'even'|'essentials'|'industry'|'consumer')=>{const values:Record<string,Record<string,number>>={essentials:{processed_foods:35,construction_materials:40,basic_goods:25},industry:{construction_materials:45,basic_goods:30,military_equipment:25},consumer:{textiles:15,processed_foods:15,basic_goods:20,consumer_goods:35,luxury_goods:15}};if(preset==='even'){const share=Math.floor(10000/goods.length)/100;setQuotas(Object.fromEntries(goods.map((key,index)=>[key,index===goods.length-1?100-share*(goods.length-1):share])));return}setQuotas(Object.fromEntries(goods.map(key=>[key,values[preset][key]||0])))};
 const togglePolicy=(key:string)=>{setError('');if(policyDraft.includes(key)){setPolicyDraft(policyDraft.filter(item=>item!==key));return}if(policyDraft.length>=2){setError('Choose no more than two social policies.');return}setPolicyDraft([...policyDraft,key])};
 const found=async()=>{if(!provinceName.trim()){setError('Enter a name for the new Province.');return}if(await act('/cities',{name:provinceName.trim()},'POST'))setProvinceName('')};
 const beginRename=(item:any)=>{setRenaming(item.ID);setRenameDraft(item.Name);setError('')};
 const saveRename=async(id:string)=>{const name=renameDraft.trim();if(name.length<2){setError('Province names must contain at least 2 characters.');return}if(await act('/cities/'+encodeURIComponent(id),{name})){setRenaming('');setRenameDraft('')}};

 return <div className="strategy-page economy-redesign">
  <EconomicDistressNotice status={data.distress}/>
  <nav className="economy-tabs" role="tablist" aria-label="Economy sections"><button type="button" role="tab" aria-selected={activeTab==='economy'} className={activeTab==='economy'?'active':''} onClick={()=>setActiveTab('economy')}><SlidersHorizontal/>National Economy</button><button type="button" role="tab" aria-selected={activeTab==='provinces'} className={activeTab==='provinces'?'active':''} onClick={()=>setActiveTab('provinces')}><MapPin/>Provinces</button></nav>
  {error&&<div className="error notice economy-inline-error" role="alert"><span>{error}</span><button type="button" onClick={()=>setError('')} aria-label="Dismiss error"><X/></button></div>}
  {activeTab==='economy'?<NationalEconomy data={data} currentGear={currentGear} previewGear={previewGear} selectedGear={selectedGear} setSelectedGear={setSelectedGear} act={act} activePolicies={active} policyDraft={policyDraft} togglePolicy={togglePolicy} policyChanged={policyChanged} policyCost={policyCost} setPolicyDraft={setPolicyDraft} quotas={quotas} savedQuotas={savedQuotas} setQuotas={setQuotas} setQuota={setQuota} total={total} quotaChanged={quotaChanged} applyQuotaPreset={applyQuotaPreset} openProvinces={()=>setActiveTab('provinces')}/>:<ProvinceManagement data={data} province={province} selectedProvinceID={selectedProvinceID} setSelectedProvinceID={setSelectedProvinceID} provinceName={provinceName} setProvinceName={setProvinceName} found={found} renaming={renaming} renameDraft={renameDraft} setRenameDraft={setRenameDraft} beginRename={beginRename} saveRename={saveRename} cancelRename={()=>{setRenaming('');setRenameDraft('')}} act={act}/>}
 </div>;
}

function NationalEconomy({data,currentGear,previewGear,selectedGear,setSelectedGear,act,activePolicies,policyDraft,togglePolicy,policyChanged,policyCost,setPolicyDraft,quotas,savedQuotas,setQuotas,setQuota,total,quotaChanged,applyQuotaPreset,openProvinces}:{data:any;currentGear:any;previewGear:any;selectedGear:string;setSelectedGear:(value:string)=>void;act:Function;activePolicies:string[];policyDraft:string[];togglePolicy:(key:string)=>void;policyChanged:boolean;policyCost:number;setPolicyDraft:(value:string[])=>void;quotas:Record<string,number>;savedQuotas:Record<string,number>;setQuotas:(value:Record<string,number>)=>void;setQuota:(key:string,value:number)=>void;total:number;quotaChanged:boolean;applyQuotaPreset:(preset:'even'|'essentials'|'industry'|'consumer')=>void;openProvinces:()=>void}){
 return <section className="national-economy-workspace">
  <header className="economy-command-header"><div><span className="eyebrow">NATIONAL ECONOMY</span><h2>{currentGear?.name}</h2><p>{currentGear?.description}</p></div><div className="economy-command-stats"><span><b>{data.politicalCapital.toFixed(1)}</b>Political capital</span><span><b>{activePolicies.length}/2</b>Active policies</span><button onClick={openProvinces}><MapPin/>Manage Provinces</button></div></header>

  <section className="economy-control-section"><SectionHeading title="Economic Gear" note="One national focus. Changes lock for seven days." help="Changing Gear costs 25 political capital and 5 Happiness. National output falls to 75% for 24 hours after a change."/><div className="compact-choice-grid gear-choices">{data.gears.map((gear:any)=>{const selected=gear.key===selectedGear,current=gear.key===data.gear;return <article className={(selected?'selected ':'')+(current?'current':'')} key={gear.key}><button className="choice-main" onClick={()=>setSelectedGear(gear.key)}><GearGlyph gear={gear.key}/><span><b>{gear.name}</b><small>{current?'Current Gear':gear.description}</small></span>{selected&&<Check/>}</button><InfoTip label={gear.name}><p>{gear.description}</p><Effects values={gear.effects}/></InfoTip></article>})}</div>{selectedGear!==data.gear&&<div className="economy-save-bar"><span><b>Change to {previewGear?.name}</b><small>25 political capital · 5 Happiness · seven-day lock</small></span><button onClick={()=>setSelectedGear(data.gear)}>Cancel</button><button className="primary" onClick={()=>act('/strategy/gear',{gear:selectedGear})}>Confirm Gear</button></div>}</section>

  <section className="economy-control-section"><SectionHeading title="Social Policies" note={`${policyDraft.length} of 2 selected`} help="You may maintain two policies. Adopting a new policy costs political capital; retaining or removing one is free."/><div className="compact-choice-grid policy-choices">{data.policies.map((policy:any)=>{const selected=policyDraft.includes(policy.key),wasActive=activePolicies.includes(policy.key);return <article className={(selected?'selected ':'')+(wasActive?'current':'')} key={policy.key}><button className="choice-main" onClick={()=>togglePolicy(policy.key)}><span><b>{policy.name}</b><small>{wasActive&&selected?'Active':wasActive?'Pending removal':selected?`${policy.cost} political capital`:`Cost: ${policy.cost}`}</small></span>{selected&&<Check/>}</button><InfoTip label={policy.name}><p>{policy.description}</p><Effects values={policy.effects}/></InfoTip></article>})}</div>{policyChanged&&<div className="economy-save-bar"><span><b>Unsaved policy changes</b><small>{policyCost?`${policyCost} political capital to adopt`:'No political capital cost'}</small></span><button onClick={()=>setPolicyDraft(activePolicies)}>Cancel</button><button className="primary" disabled={policyCost>data.politicalCapital} onClick={()=>act('/strategy/policies',{policies:policyDraft})}>Save Policies</button></div>}</section>

  <section className="production-console"><header><div><span className="eyebrow">INDUSTRIAL ALLOCATION</span><h2>Commodity production</h2></div><div className="production-total"><span>Allocated</span><b className={total>100.001?'invalid':''}>{total.toFixed(1)}%</b><i><em style={{width:`${Math.min(100,total)}%`}}/></i></div></header><div className="production-presets"><span>Presets</span><button onClick={()=>applyQuotaPreset('even')}>Even</button><button onClick={()=>applyQuotaPreset('essentials')}>Essentials</button><button onClick={()=>applyQuotaPreset('industry')}>Industry</button><button onClick={()=>applyQuotaPreset('consumer')}>Consumer</button><InfoTip label="How allocation works"><p>Drag any row or enter a percentage. Raising one allocation automatically draws capacity proportionally from the others. Saved allocations may be set to zero.</p></InfoTip></div><div className="production-table"><div className="production-table-head"><span>Commodity</span><span>Allocation</span><span>Share</span><span>Daily output</span></div>{goods.map(key=><ProductionRow key={key} resource={key} amount={Number(quotas[key]||0)} output={Number(data.result.production[key]||0)} stockpile={Number(data.stockpiles[key]||0)} recipe={data.recipes[key]||{}} setQuota={setQuota}/>)}</div>{quotaChanged&&<div className="economy-save-bar production-save"><span><b>Production plan changed</b><small>{total<99.999?`${(100-total).toFixed(1)}% capacity will remain idle`:'All capacity assigned'}</small></span><button onClick={()=>setQuotas({...savedQuotas})}>Reset</button><button className="primary" disabled={total>100.001} onClick={()=>act('/strategy/quotas',{quotas})}>Save Production</button></div>}</section>
 </section>;
}

function ProductionRow({resource,amount,output,stockpile,recipe,setQuota}:{resource:string;amount:number;output:number;stockpile:number;recipe:Record<string,number>;setQuota:(key:string,value:number)=>void}){return <article className={amount>0?'active':''}><div className="production-name"><ResourceIcon type={resource as any}/><span><b>{labels[resource]}</b><small>{stockpile.toLocaleString()} t stored</small></span><InfoTip label={`${labels[resource]} recipe`}>{Object.keys(recipe).length?<div className="recipe-tooltip">{Object.entries(recipe).map(([key,value])=><span key={key}><b>{Number(value).toFixed(2)} t</b> {labels[key]||key}</span>)}</div>:<p>No input commodities required.</p>}</InfoTip></div><input className="production-slider" aria-label={`${labels[resource]} allocation`} type="range" step="0.5" min="0" max="100" value={amount} onChange={event=>setQuota(resource,Number(event.target.value))}/><label className="production-number"><input aria-label={`${labels[resource]} allocation percent`} type="number" step="0.1" min="0" max="100" value={Number(amount.toFixed(1))} onChange={event=>setQuota(resource,Number(event.target.value))}/><span>%</span></label><strong>+{output.toFixed(1)} t</strong></article>}

function ProvinceManagement({data,province,selectedProvinceID,setSelectedProvinceID,provinceName,setProvinceName,found,renaming,renameDraft,setRenameDraft,beginRename,saveRename,cancelRename,act}:{data:any;province:any;selectedProvinceID:string;setSelectedProvinceID:(value:string)=>void;provinceName:string;setProvinceName:(value:string)=>void;found:()=>void;renaming:string;renameDraft:string;setRenameDraft:(value:string)=>void;beginRename:(province:any)=>void;saveRename:(id:string)=>void;cancelRename:()=>void;act:Function}){
 const metrics=data.provinceCivicMetrics?.[province?.ID],production=data.result.provinceProduction?.[province?.ID]||{},factors=data.result.provinceFactors?.[province?.ID]||{};
 return <section className="province-management-workspace">
  <header className="province-command-header"><label><span>Province</span><select value={province?.ID||selectedProvinceID} onChange={event=>{setSelectedProvinceID(event.target.value);cancelRename()}}>{data.provinces.map((item:any)=><option value={item.ID} key={item.ID}>{item.IsCapital?'Capital · ':''}{item.Name}</option>)}</select></label>{province&&<><div className="province-command-stat"><span>Infrastructure</span><b>{Math.round(province.Infra).toLocaleString()}</b></div><div className="province-command-stat"><span>Economic capacity</span><b>{province.UpgradesUsed}/{province.UpgradeCapacity}</b></div><div className="province-command-stat"><span>Civic capacity</span><b>{province.CivicUsed}/{province.CivicCapacity}</b></div><button className="province-expand-jump" onClick={()=>document.getElementById('province-expansion')?.scrollIntoView({behavior:'smooth'})}><Plus/>Expand nation</button></>}</header>
  {province&&<>
   <ProvinceEconomySnapshot province={province} metrics={metrics} production={production} factors={factors} extractionMultiplier={data.result.extractionMultiplier} industryMultiplier={data.result.industryMultiplier}/>
   <div className="province-workbench">
    <section className="province-development-column"><ProvinceTitle p={province} editing={renaming===province.ID} draft={renameDraft} setDraft={setRenameDraft} start={()=>beginRename(province)} cancel={cancelRename} save={()=>saveRename(province.ID)}/><div className="province-specialization-row"><label><span>Specialization</span><select value={province.Specialization} onChange={event=>act('/strategy/province',{provinceID:province.ID,specialization:event.target.value,developmentInvestment:0})}>{Object.entries(specializations).map(([key,item])=><option value={key} key={key}>{item.name}</option>)}</select></label><p>{specializations[province.Specialization]?.description}</p><InfoTip label="Resource deposits"><div className="deposit-tooltip">{Object.entries(province.Deposits).map(([key,value])=><span key={key}><b>{labels[key]}</b>{Number(value).toFixed(2)}× richness</span>)}</div></InfoTip></div><div className="infrastructure-control"><div><span className="eyebrow">INFRASTRUCTURE</span><b>{Math.round(province.Infra).toLocaleString()}</b><small>Next economic capacity at {province.NextUpgradeCapacityAt}</small></div>{[10,50,100].map(amount=><button key={amount} onClick={()=>act('/economy/development',{cityID:province.ID,kind:'infrastructure',amount},'POST')}><b>+{amount}</b><span>{money(province.InfrastructureQuotes[String(amount)])}</span></button>)}<InfoTip label="Infrastructure"><p>Infrastructure raises population and tax capacity. It never consumes an economic upgrade slot; every additional 50 Infrastructure unlocks another.</p></InfoTip></div><section className="province-upgrades"><SectionHeading title="Economic upgrades" note={`${province.UpgradesUsed} of ${province.UpgradeCapacity} capacity used`} help="Each category caps at level 15. Returns begin diminishing around level 8. Lowering a level is immediate and provides no refund."/>{data.provinceUpgradeTypes.map((upgrade:any)=><ProvinceUpgrade key={upgrade.key} province={province} upgrade={upgrade} act={act}/>)}</section></section>
    <CivicInstitutions province={province} metrics={metrics} definitions={data.civicInstitutions||[]} stockpiles={data.stockpiles||{}} technology={Number(data.technology||0)} build={(key:string)=>act('/economy/improvements',{cityID:province.ID,building:key},'POST')} deconstruct={(key:string)=>act('/economy/improvements/deconstruct',{cityID:province.ID,building:key},'POST')}/>
   </div>
  </>}
  <details className="province-expansion" id="province-expansion"><summary><span><b>Found Province {data.expansion.provinceCount+1}</b><small>{money(data.expansion.cashCost)} · {Number(data.expansion.constructionMaterials).toLocaleString()} t Construction Materials</small></span><ChevronDown/></summary><div><div className="expansion-detail-line"><p>Expansion applies −{data.expansion.happinessStrain} temporary Happiness strain. Current cost modifiers: Gear ×{Number(data.expansion.gearModifier).toFixed(2)}, policies ×{Number(data.expansion.policyModifier).toFixed(2)}.</p><InfoTip label="Expansion cost"><p>{data.expansion.formula}</p><p>Each Province makes the next one more expensive.</p></InfoTip></div>{data.expansion.nextProvinceAt?<p className="cooldown">Available {new Date(data.expansion.nextProvinceAt).toLocaleString()}</p>:<div className="found-province"><input value={provinceName} minLength={2} maxLength={30} placeholder="Province name" onChange={event=>setProvinceName(event.target.value)}/><button className="primary" onClick={found}><Plus/>Found Province</button></div>}</div></details>
 </section>;
}

function ProvinceEconomySnapshot({province,metrics,production,factors,extractionMultiplier,industryMultiplier}:{province:any;metrics:any;production:Record<string,number>;factors:any;extractionMultiplier:number;industryMultiplier:number}){const primary=new Set(['foodstuffs','timber','fibers','basic_metals','energy','strategic_minerals']),items=Object.entries(production).filter(([,amount])=>Number(amount)>0).sort((a,b)=>Number(b[1])-Number(a[1])),employment=Number(metrics?.employmentRate||factors.employmentRate||0),disease=Number(metrics?.disease||factors.diseaseRate||0),crime=Number(metrics?.crime||factors.crimeRate||0),operating=Number(factors.operationalFactor||1);return <section className="province-snapshot"><div className="province-vitals"><article><span>Employment</span><b>{employment.toFixed(1)}%</b><InfoTip label="Employment"><p>Employment directly supports tax collection and production. Build commercial and transit institutions to improve it.</p></InfoTip></article><article><span>Disease</span><b className={disease>.02?'warning':''}>{(disease*100).toFixed(1)}%</b><InfoTip label="Disease"><p>Disease reduces effective population and production. Hospitals reduce it; industrial pollution can increase it.</p></InfoTip></article><article><span>Crime</span><b className={crime>.03?'warning':''}>{(crime*100).toFixed(1)}%</b><InfoTip label="Crime"><p>Crime reduces effective population and production. Police, employment, and Education help control it.</p></InfoTip></article><article><span>Operating efficiency</span><b className={operating<1?'warning':''}>{operating.toFixed(3)}×</b><InfoTip label="Operating efficiency"><p>The combined result of employment, disease, crime, and national conditions.</p></InfoTip></article></div><div className="province-output-strip"><span className="eyebrow">DAILY OUTPUT</span>{items.length?items.map(([key,amount])=><article key={key}><ResourceIcon type={key as any}/><span>{labels[key]||key}</span><b>+{Number(amount).toFixed(2)} t</b><InfoTip label={`${labels[key]||key} output`}><p>{primary.has(key)?`${Math.round(province.Infra)} Infrastructure × ${Number(province.Deposits?.[key]||0).toFixed(2)}× richness × ${Number(extractionMultiplier||1).toFixed(3)}× national extraction × ${operating.toFixed(3)}× efficiency.`:`Driven by Infrastructure, ${Number(industryMultiplier||1).toFixed(3)}× national industry, production allocation, Province upgrades, and ${operating.toFixed(3)}× efficiency.`}</p></InfoTip></article>):<p>No output projected.</p>}</div></section>}

function ProvinceUpgrade({province,upgrade,act}:{province:any;upgrade:any;act:Function}){const level=Number(province.Upgrades[upgrade.key]||0),capacityFull=Number(province.UpgradesUsed)>=Number(province.UpgradeCapacity),capped=level>=15||capacityFull;return <article className="province-upgrade-row"><div><b>{upgrade.name}</b><span>Level {level} / 15</span>{level>=8&&level<15&&<small>Diminishing returns</small>}</div><UpgradeBenefits current={province.CurrentUpgradeBenefits?.[upgrade.key]} next={province.NextUpgradeBenefits?.[upgrade.key]}/><InfoTip label={upgrade.name}><p>{upgrade.descriptionText||upgrade.description}</p></InfoTip><button className="upgrade-lower" disabled={level<=0} onClick={()=>act('/strategy/province/upgrade',{provinceID:province.ID,upgrade:upgrade.key,action:'downgrade'},'POST')}>−</button><button className="upgrade-raise" disabled={capped} onClick={()=>act('/strategy/province/upgrade',{provinceID:province.ID,upgrade:upgrade.key,action:'upgrade'},'POST')}>{level>=15?'Capped':capacityFull?'Needs capacity':<>Raise · {money(province.UpgradeQuotes[upgrade.key])}</>}</button></article>}

function SectionHeading({title,note,help}:{title:string;note:string;help:string}){return <header className="economy-section-heading"><div><h3>{title}</h3><span>{note}</span></div><InfoTip label={title}><p>{help}</p></InfoTip></header>}
function UpgradeBenefits({current={},next={}}:{current?:Record<string,number>;next?:Record<string,number>}){const names=Object.keys(next);return <span className="upgrade-benefits">{names.slice(0,2).map(name=><span key={name}><small>{name}</small><b>{Number(current[name]||0).toFixed(1)}% <i>→</i> {Number(next[name]||0).toFixed(1)}%</b></span>)}</span>}
function ProvinceTitle({p,editing,draft,setDraft,start,cancel,save}:{p:any;editing:boolean;draft:string;setDraft:(value:string)=>void;start:()=>void;cancel:()=>void;save:()=>void}){return <div className="province-head"><div className="province-identity"><span className="eyebrow">{p.IsCapital?'CAPITAL PROVINCE':'PROVINCE'}</span>{editing?<div className="province-rename-editor"><input autoFocus minLength={2} maxLength={30} value={draft} onChange={event=>setDraft(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')save();if(event.key==='Escape')cancel()}} aria-label={`Rename ${p.Name}`}/><button className="save" onClick={save} disabled={draft.trim().length<2} title="Save Province name"><Check/></button><button onClick={cancel} title="Cancel rename"><X/></button></div>:<div className="province-name-row"><h2>{p.Name}</h2><button className="province-rename-trigger" onClick={start}><Pencil/>Rename</button></div>}</div></div>}

function CivicInstitutions({province,metrics,definitions,stockpiles,technology,build,deconstruct}:{province:any;metrics:any;definitions:any[];stockpiles:Record<string,number>;technology:number;build:(key:string)=>Promise<boolean>;deconstruct:(key:string)=>Promise<boolean>}){const[details,setDetails]=useState<any>();const full=Number(province.CivicUsed)>=Number(province.CivicCapacity);const remove=async(item:any)=>{if(!confirm(`Deconstruct one ${item.name}? No Treasury will be returned; 75% of its resource construction cost will be recovered.`))return false;return deconstruct(item.key)};return <section className="civic-console"><SectionHeading title="Civic Institutions" note={`${province.CivicUsed} of ${province.CivicCapacity} capacity used`} help="Institutions shape employment, tax collection, disease, crime, Education, and local Satisfaction. Open any institution for its exact effects and construction cost."/>{metrics&&<div className="civic-summary"><span><b>{Number(metrics.employmentRate).toFixed(1)}%</b>Employment</span><span><b>{Number(metrics.taxCollectionMultiplier).toFixed(3)}×</b>Tax collection</span><span><b>{money(metrics.dailyUpkeep)}</b>Daily upkeep</span></div>}<div className="civic-list">{definitions.map(item=>{const quantity=Number(province.Institutions?.[item.key]||0),atTypeCap=item.maxPerProvince>0&&quantity>=item.maxPerProvince,locked=technology<Number(item.minTech||0);return <article key={item.key}><button className="civic-name" onClick={()=>setDetails(item)}><span><small>{item.category}</small><b>{item.name}</b></span><strong>{quantity}/{item.maxPerProvince}</strong></button><span className="civic-quick-cost">{money(item.cashCost)}</span><button className="civic-remove" disabled={quantity<1} onClick={()=>void remove(item)} aria-label={`Deconstruct ${item.name}`}>−</button><button className="civic-build" disabled={full||atTypeCap||locked} onClick={()=>void build(item.key)}>{locked?`Tech ${item.minTech}`:atTypeCap?'Limit':full?'No capacity':'Build'}</button></article>})}</div>{details&&<CivicModal details={details} province={province} stockpiles={stockpiles} technology={technology} full={full} close={()=>setDetails(undefined)} remove={remove} build={build}/>}</section>}
function CivicModal({details,province,stockpiles,technology,full,close,remove,build}:{details:any;province:any;stockpiles:Record<string,number>;technology:number;full:boolean;close:()=>void;remove:(item:any)=>Promise<boolean>;build:(key:string)=>Promise<boolean>}){return <div className="civic-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)close()}}><section className="civic-modal" role="dialog" aria-modal="true" aria-labelledby="civic-detail-title"><button className="civic-modal-close" onClick={close} aria-label="Close institution details"><X/></button><span className="eyebrow">{details.category}</span><h2 id="civic-detail-title">{details.name}</h2><p>{details.description}</p><div className="civic-effects">{institutionEffects(details).map(effect=><span key={effect}>{effect}</span>)}</div><h3>Construction cost</h3><div className="civic-costs"><span><b>{money(details.cashCost)}</b>Treasury</span>{Object.entries(details.resourceCosts||{}).map(([key,value])=><span className={Number(stockpiles[key]||0)<Number(value)?'missing':''} key={key}><b>{Number(value).toLocaleString()} t</b>{labels[key]||key}<small>{Number(stockpiles[key]||0).toLocaleString()} t available</small></span>)}</div><p className="civic-upkeep"><b>Daily upkeep:</b> {money(details.dailyUpkeep)} · Province limit {details.maxPerProvince}</p><div className="civic-modal-actions"><button className="danger" disabled={Number(province.Institutions?.[details.key]||0)<1} onClick={async()=>{if(await remove(details))close()}}>Deconstruct one</button><button className="primary" disabled={full||Number(province.Institutions?.[details.key]||0)>=Number(details.maxPerProvince)||technology<Number(details.minTech||0)} onClick={async()=>{if(await build(details.key))close()}}>Build {details.name}</button></div></section></div>}
function institutionEffects(item:any){const effects:string[]=[];if(item.employment)effects.push(`Employment +${Number(item.employment).toFixed(1)} points`);if(item.taxCollection)effects.push(`Tax collection +${Number(item.taxCollection).toFixed(1)}%`);if(item.commerce)effects.push(`Province Commerce +${Number(item.commerce).toFixed(1)}%`);if(item.education)effects.push(`Education progress +${Number(item.education).toFixed(1)}`);if(item.happiness)effects.push(`Local Satisfaction +${Number(item.happiness).toFixed(1)}`);if(item.diseaseReduction)effects.push(`Disease −${(Number(item.diseaseReduction)*100).toFixed(1)} points`);if(item.crimeReduction)effects.push(`Crime −${(Number(item.crimeReduction)*100).toFixed(1)} points`);if(item.pollution)effects.push(`Pollution ${Number(item.pollution)>0?'+':''}${Number(item.pollution).toFixed(1)}`);return effects}
